// Country Mastery — daily geography guessing game data layer

export interface GeoCountry {
  name: string;
  code: string; // ISO 3166-1 alpha-2 (lowercase)
  flag: string;
  capital: string;
  continent: string;
  population: string;
  funFact: string;
  neighbors: string[];
}

export interface GeoPuzzle {
  date: string;
  country: GeoCountry;
}

// ---------------------------------------------------------------------------
// Country bank (~60 countries, diverse continents)
// ---------------------------------------------------------------------------

export const countries: GeoCountry[] = [
  // ── Africa ────────────────────────────────────────────────────────────────
  {
    name: "Nigeria",
    code: "ng",
    flag: "\u{1F1F3}\u{1F1EC}",
    capital: "Abuja",
    continent: "Africa",
    population: "200-250 million",
    funFact: "Has the largest economy in Africa and is called the 'Giant of Africa'.",
    neighbors: ["Benin", "Chad", "Cameroon", "Niger"],
  },
  {
    name: "Kenya",
    code: "ke",
    flag: "\u{1F1F0}\u{1F1EA}",
    capital: "Nairobi",
    continent: "Africa",
    population: "50-60 million",
    funFact: "Home to the Great Wildebeest Migration across the Masai Mara.",
    neighbors: ["Tanzania", "Uganda", "Somalia", "Ethiopia"],
  },
  {
    name: "Egypt",
    code: "eg",
    flag: "\u{1F1EA}\u{1F1EC}",
    capital: "Cairo",
    continent: "Africa",
    population: "100-110 million",
    funFact: "The Great Pyramid of Giza is the only surviving ancient wonder of the world.",
    neighbors: ["Libya", "Sudan", "Israel", "Palestine"],
  },
  {
    name: "South Africa",
    code: "za",
    flag: "\u{1F1FF}\u{1F1E6}",
    capital: "Pretoria",
    continent: "Africa",
    population: "55-65 million",
    funFact: "Has three capital cities: Pretoria, Cape Town, and Bloemfontein.",
    neighbors: ["Namibia", "Botswana", "Zimbabwe", "Mozambique"],
  },
  {
    name: "Morocco",
    code: "ma",
    flag: "\u{1F1F2}\u{1F1E6}",
    capital: "Rabat",
    continent: "Africa",
    population: "35-40 million",
    funFact: "Home to the oldest continuously operating university in the world (University of al-Qarawiyyin).",
    neighbors: ["Algeria", "Mauritania", "Spain"],
  },
  {
    name: "Ethiopia",
    code: "et",
    flag: "\u{1F1EA}\u{1F1F9}",
    capital: "Addis Ababa",
    continent: "Africa",
    population: "110-125 million",
    funFact: "Uses its own calendar that is 7-8 years behind the Gregorian calendar.",
    neighbors: ["Eritrea", "Djibouti", "Somalia", "Kenya", "Sudan"],
  },
  {
    name: "Ghana",
    code: "gh",
    flag: "\u{1F1EC}\u{1F1ED}",
    capital: "Accra",
    continent: "Africa",
    population: "30-35 million",
    funFact: "Was the first sub-Saharan African country to gain independence from colonial rule (1957).",
    neighbors: ["Ivory Coast", "Togo", "Burkina Faso"],
  },
  {
    name: "Madagascar",
    code: "mg",
    flag: "\u{1F1F2}\u{1F1EC}",
    capital: "Antananarivo",
    continent: "Africa",
    population: "25-30 million",
    funFact: "About 90% of its wildlife is found nowhere else on Earth.",
    neighbors: ["Mozambique", "Comoros"],
  },

  // ── Asia ───────────────────────────────────────────────────────────────────
  {
    name: "Japan",
    code: "jp",
    flag: "\u{1F1EF}\u{1F1F5}",
    capital: "Tokyo",
    continent: "Asia",
    population: "125-130 million",
    funFact: "Has over 6,800 islands and more than 100 active volcanoes.",
    neighbors: ["South Korea", "China", "Russia"],
  },
  {
    name: "India",
    code: "in",
    flag: "\u{1F1EE}\u{1F1F3}",
    capital: "New Delhi",
    continent: "Asia",
    population: "1.4-1.5 billion",
    funFact: "Has the most languages spoken of any country — over 780 languages.",
    neighbors: ["Pakistan", "China", "Nepal", "Bangladesh", "Myanmar"],
  },
  {
    name: "South Korea",
    code: "kr",
    flag: "\u{1F1F0}\u{1F1F7}",
    capital: "Seoul",
    continent: "Asia",
    population: "50-55 million",
    funFact: "Has the fastest average internet speed in the world.",
    neighbors: ["North Korea", "Japan", "China"],
  },
  {
    name: "Thailand",
    code: "th",
    flag: "\u{1F1F9}\u{1F1ED}",
    capital: "Bangkok",
    continent: "Asia",
    population: "70-75 million",
    funFact: "Bangkok's full ceremonial name has 168 characters, making it one of the longest place names.",
    neighbors: ["Myanmar", "Laos", "Cambodia", "Malaysia"],
  },
  {
    name: "Vietnam",
    code: "vn",
    flag: "\u{1F1FB}\u{1F1F3}",
    capital: "Hanoi",
    continent: "Asia",
    population: "95-100 million",
    funFact: "Is the world's second-largest coffee exporter after Brazil.",
    neighbors: ["China", "Laos", "Cambodia"],
  },
  {
    name: "Turkey",
    code: "tr",
    flag: "\u{1F1F9}\u{1F1F7}",
    capital: "Ankara",
    continent: "Asia",
    population: "85-90 million",
    funFact: "Spans two continents — Europe and Asia — split by the Bosphorus strait.",
    neighbors: ["Greece", "Bulgaria", "Georgia", "Armenia", "Iran", "Iraq", "Syria"],
  },
  {
    name: "Philippines",
    code: "ph",
    flag: "\u{1F1F5}\u{1F1ED}",
    capital: "Manila",
    continent: "Asia",
    population: "110-115 million",
    funFact: "Made up of over 7,600 islands and sends the most text messages per capita in the world.",
    neighbors: ["Taiwan", "Vietnam", "Malaysia", "Indonesia"],
  },
  {
    name: "Indonesia",
    code: "id",
    flag: "\u{1F1EE}\u{1F1E9}",
    capital: "Jakarta",
    continent: "Asia",
    population: "270-280 million",
    funFact: "Is the world's largest archipelago with over 17,000 islands.",
    neighbors: ["Malaysia", "Papua New Guinea", "East Timor", "Australia"],
  },
  {
    name: "Mongolia",
    code: "mn",
    flag: "\u{1F1F2}\u{1F1F3}",
    capital: "Ulaanbaatar",
    continent: "Asia",
    population: "3-4 million",
    funFact: "Is the most sparsely populated country in the world.",
    neighbors: ["Russia", "China"],
  },
  {
    name: "Nepal",
    code: "np",
    flag: "\u{1F1F3}\u{1F1F5}",
    capital: "Kathmandu",
    continent: "Asia",
    population: "30-35 million",
    funFact: "Has the only non-rectangular national flag in the world — it's two stacked triangles.",
    neighbors: ["India", "China"],
  },
  {
    name: "Saudi Arabia",
    code: "sa",
    flag: "\u{1F1F8}\u{1F1E6}",
    capital: "Riyadh",
    continent: "Asia",
    population: "35-40 million",
    funFact: "Has no rivers and is one of the driest countries on Earth.",
    neighbors: ["Jordan", "Iraq", "Kuwait", "Bahrain", "Qatar", "UAE", "Oman", "Yemen"],
  },
  {
    name: "Israel",
    code: "il",
    flag: "\u{1F1EE}\u{1F1F1}",
    capital: "Jerusalem",
    continent: "Asia",
    population: "9-10 million",
    funFact: "The Dead Sea, shared with Jordan, is the lowest point on Earth's surface.",
    neighbors: ["Lebanon", "Syria", "Jordan", "Egypt", "Palestine"],
  },

  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    name: "France",
    code: "fr",
    flag: "\u{1F1EB}\u{1F1F7}",
    capital: "Paris",
    continent: "Europe",
    population: "65-70 million",
    funFact: "Is the most visited country in the world with ~90 million tourists per year.",
    neighbors: ["Germany", "Spain", "Italy", "Belgium", "Switzerland"],
  },
  {
    name: "Germany",
    code: "de",
    flag: "\u{1F1E9}\u{1F1EA}",
    capital: "Berlin",
    continent: "Europe",
    population: "83-85 million",
    funFact: "Has over 1,500 different types of beer and the world's oldest beer purity law (Reinheitsgebot, 1516).",
    neighbors: ["France", "Poland", "Czech Republic", "Austria", "Netherlands", "Denmark"],
  },
  {
    name: "Italy",
    code: "it",
    flag: "\u{1F1EE}\u{1F1F9}",
    capital: "Rome",
    continent: "Europe",
    population: "60-65 million",
    funFact: "Contains two entirely independent countries within its borders: Vatican City and San Marino.",
    neighbors: ["France", "Switzerland", "Austria", "Slovenia"],
  },
  {
    name: "Spain",
    code: "es",
    flag: "\u{1F1EA}\u{1F1F8}",
    capital: "Madrid",
    continent: "Europe",
    population: "47-50 million",
    funFact: "Has more bars per capita than any other European country.",
    neighbors: ["France", "Portugal", "Andorra", "Morocco"],
  },
  {
    name: "Portugal",
    code: "pt",
    flag: "\u{1F1F5}\u{1F1F9}",
    capital: "Lisbon",
    continent: "Europe",
    population: "10-11 million",
    funFact: "Is home to the world's oldest bookstore, Livraria Bertrand, open since 1732.",
    neighbors: ["Spain"],
  },
  {
    name: "Norway",
    code: "no",
    flag: "\u{1F1F3}\u{1F1F4}",
    capital: "Oslo",
    continent: "Europe",
    population: "5-6 million",
    funFact: "Has more than 1,000 fjords carved by glaciers over millions of years.",
    neighbors: ["Sweden", "Finland", "Russia"],
  },
  {
    name: "Sweden",
    code: "se",
    flag: "\u{1F1F8}\u{1F1EA}",
    capital: "Stockholm",
    continent: "Europe",
    population: "10-11 million",
    funFact: "Has an Ice Hotel that is rebuilt from scratch every winter.",
    neighbors: ["Norway", "Finland", "Denmark"],
  },
  {
    name: "Greece",
    code: "gr",
    flag: "\u{1F1EC}\u{1F1F7}",
    capital: "Athens",
    continent: "Europe",
    population: "10-11 million",
    funFact: "Athens is one of the oldest cities in the world, inhabited for over 3,400 years.",
    neighbors: ["Turkey", "Bulgaria", "North Macedonia", "Albania"],
  },
  {
    name: "Poland",
    code: "pl",
    flag: "\u{1F1F5}\u{1F1F1}",
    capital: "Warsaw",
    continent: "Europe",
    population: "38-40 million",
    funFact: "Is home to the Wieliczka Salt Mine, an underground cathedral carved entirely from salt.",
    neighbors: ["Germany", "Czech Republic", "Slovakia", "Ukraine", "Belarus", "Lithuania"],
  },
  {
    name: "Ireland",
    code: "ie",
    flag: "\u{1F1EE}\u{1F1EA}",
    capital: "Dublin",
    continent: "Europe",
    population: "5-6 million",
    funFact: "Has no native snakes — legend says St. Patrick drove them all out.",
    neighbors: ["United Kingdom"],
  },
  {
    name: "Switzerland",
    code: "ch",
    flag: "\u{1F1E8}\u{1F1ED}",
    capital: "Bern",
    continent: "Europe",
    population: "8-9 million",
    funFact: "Has four official languages: German, French, Italian, and Romansh.",
    neighbors: ["Germany", "France", "Italy", "Austria", "Liechtenstein"],
  },
  {
    name: "Croatia",
    code: "hr",
    flag: "\u{1F1ED}\u{1F1F7}",
    capital: "Zagreb",
    continent: "Europe",
    population: "3-4 million",
    funFact: "The necktie (cravat) was invented here — named after Croatian soldiers.",
    neighbors: ["Slovenia", "Hungary", "Serbia", "Bosnia and Herzegovina", "Montenegro"],
  },
  {
    name: "Iceland",
    code: "is",
    flag: "\u{1F1EE}\u{1F1F8}",
    capital: "Reykjavik",
    continent: "Europe",
    population: "350-400 thousand",
    funFact: "Has no army, navy, or air force and is home to the world's oldest parliament (Althing, 930 AD).",
    neighbors: ["Greenland", "United Kingdom"],
  },

  // ── North America ──────────────────────────────────────────────────────────
  {
    name: "Mexico",
    code: "mx",
    flag: "\u{1F1F2}\u{1F1FD}",
    capital: "Mexico City",
    continent: "North America",
    population: "125-135 million",
    funFact: "Mexico City was built on top of the ancient Aztec capital Tenochtitlan.",
    neighbors: ["United States", "Guatemala", "Belize"],
  },
  {
    name: "Canada",
    code: "ca",
    flag: "\u{1F1E8}\u{1F1E6}",
    capital: "Ottawa",
    continent: "North America",
    population: "38-40 million",
    funFact: "Has more lakes than all other countries combined — over 2 million.",
    neighbors: ["United States"],
  },
  {
    name: "Cuba",
    code: "cu",
    flag: "\u{1F1E8}\u{1F1FA}",
    capital: "Havana",
    continent: "North America",
    population: "11-12 million",
    funFact: "Classic American cars from the 1950s are still widely used as daily transport.",
    neighbors: ["United States", "Jamaica", "Haiti", "Mexico"],
  },
  {
    name: "Jamaica",
    code: "jm",
    flag: "\u{1F1EF}\u{1F1F2}",
    capital: "Kingston",
    continent: "North America",
    population: "2-3 million",
    funFact: "Birthplace of reggae music and home of Bob Marley.",
    neighbors: ["Cuba", "Haiti", "Colombia"],
  },
  {
    name: "Costa Rica",
    code: "cr",
    flag: "\u{1F1E8}\u{1F1F7}",
    capital: "San José",
    continent: "North America",
    population: "5-6 million",
    funFact: "Has no army — it was abolished in 1948 and the budget goes to education.",
    neighbors: ["Nicaragua", "Panama"],
  },
  {
    name: "Panama",
    code: "pa",
    flag: "\u{1F1F5}\u{1F1E6}",
    capital: "Panama City",
    continent: "North America",
    population: "4-5 million",
    funFact: "The Panama Canal connects the Atlantic and Pacific oceans across just 82 km.",
    neighbors: ["Costa Rica", "Colombia"],
  },
  {
    name: "Guatemala",
    code: "gt",
    flag: "\u{1F1EC}\u{1F1F9}",
    capital: "Guatemala City",
    continent: "North America",
    population: "17-18 million",
    funFact: "Was the heartland of the ancient Maya civilization.",
    neighbors: ["Mexico", "Belize", "Honduras", "El Salvador"],
  },

  // ── South America ──────────────────────────────────────────────────────────
  {
    name: "Brazil",
    code: "br",
    flag: "\u{1F1E7}\u{1F1F7}",
    capital: "Brasília",
    continent: "South America",
    population: "210-215 million",
    funFact: "The Amazon Rainforest produces about 20% of the world's oxygen.",
    neighbors: ["Argentina", "Colombia", "Peru", "Venezuela", "Uruguay", "Paraguay"],
  },
  {
    name: "Argentina",
    code: "ar",
    flag: "\u{1F1E6}\u{1F1F7}",
    capital: "Buenos Aires",
    continent: "South America",
    population: "45-50 million",
    funFact: "Invented the tango dance and has the widest avenue in the world (Avenida 9 de Julio).",
    neighbors: ["Chile", "Brazil", "Uruguay", "Paraguay", "Bolivia"],
  },
  {
    name: "Chile",
    code: "cl",
    flag: "\u{1F1E8}\u{1F1F1}",
    capital: "Santiago",
    continent: "South America",
    population: "19-20 million",
    funFact: "Is the longest north-south country in the world, stretching 4,300 km.",
    neighbors: ["Argentina", "Bolivia", "Peru"],
  },
  {
    name: "Colombia",
    code: "co",
    flag: "\u{1F1E8}\u{1F1F4}",
    capital: "Bogotá",
    continent: "South America",
    population: "50-55 million",
    funFact: "Is the world's leading producer of emeralds.",
    neighbors: ["Venezuela", "Brazil", "Peru", "Ecuador", "Panama"],
  },
  {
    name: "Peru",
    code: "pe",
    flag: "\u{1F1F5}\u{1F1EA}",
    capital: "Lima",
    continent: "South America",
    population: "33-35 million",
    funFact: "Home to Machu Picchu, the 'Lost City of the Incas', at 2,430 meters above sea level.",
    neighbors: ["Ecuador", "Colombia", "Brazil", "Bolivia", "Chile"],
  },
  {
    name: "Uruguay",
    code: "uy",
    flag: "\u{1F1FA}\u{1F1FE}",
    capital: "Montevideo",
    continent: "South America",
    population: "3-4 million",
    funFact: "Was the first country to legalize cannabis nationwide and hosted the first FIFA World Cup in 1930.",
    neighbors: ["Argentina", "Brazil"],
  },
  {
    name: "Ecuador",
    code: "ec",
    flag: "\u{1F1EA}\u{1F1E8}",
    capital: "Quito",
    continent: "South America",
    population: "17-18 million",
    funFact: "Named after the equator — Quito sits just 25 km south of latitude 0°.",
    neighbors: ["Colombia", "Peru"],
  },

  // ── Oceania ────────────────────────────────────────────────────────────────
  {
    name: "Australia",
    code: "au",
    flag: "\u{1F1E6}\u{1F1FA}",
    capital: "Canberra",
    continent: "Oceania",
    population: "25-27 million",
    funFact: "Has more kangaroos than people — roughly 50 million kangaroos.",
    neighbors: ["New Zealand", "Indonesia", "Papua New Guinea"],
  },
  {
    name: "New Zealand",
    code: "nz",
    flag: "\u{1F1F3}\u{1F1FF}",
    capital: "Wellington",
    continent: "Oceania",
    population: "5-6 million",
    funFact: "Was the first country to give women the right to vote (1893) and has more sheep than people.",
    neighbors: ["Australia", "Fiji", "Tonga"],
  },
  {
    name: "Fiji",
    code: "fj",
    flag: "\u{1F1EB}\u{1F1EF}",
    capital: "Suva",
    continent: "Oceania",
    population: "900 thousand - 1 million",
    funFact: "Made up of 333 islands but only about 110 are permanently inhabited.",
    neighbors: ["Tonga", "Vanuatu", "New Zealand"],
  },
  {
    name: "Papua New Guinea",
    code: "pg",
    flag: "\u{1F1F5}\u{1F1EC}",
    capital: "Port Moresby",
    continent: "Oceania",
    population: "9-10 million",
    funFact: "Has over 840 languages — more than any other country on Earth.",
    neighbors: ["Indonesia", "Australia", "Solomon Islands"],
  },

  // ── More Asia ──────────────────────────────────────────────────────────────
  {
    name: "Bangladesh",
    code: "bd",
    flag: "\u{1F1E7}\u{1F1E9}",
    capital: "Dhaka",
    continent: "Asia",
    population: "165-175 million",
    funFact: "Has the world's largest river delta — the Ganges-Brahmaputra Delta.",
    neighbors: ["India", "Myanmar"],
  },
  {
    name: "Pakistan",
    code: "pk",
    flag: "\u{1F1F5}\u{1F1F0}",
    capital: "Islamabad",
    continent: "Asia",
    population: "220-230 million",
    funFact: "K2, the world's second-highest mountain, is on its border with China.",
    neighbors: ["India", "China", "Afghanistan", "Iran"],
  },
  {
    name: "Sri Lanka",
    code: "lk",
    flag: "\u{1F1F1}\u{1F1F0}",
    capital: "Sri Jayawardenepura Kotte",
    continent: "Asia",
    population: "21-23 million",
    funFact: "Known as the 'Pearl of the Indian Ocean' and is one of the world's top tea producers.",
    neighbors: ["India", "Maldives"],
  },

  // ── More Europe ────────────────────────────────────────────────────────────
  {
    name: "Finland",
    code: "fi",
    flag: "\u{1F1EB}\u{1F1EE}",
    capital: "Helsinki",
    continent: "Europe",
    population: "5-6 million",
    funFact: "Has about 3 million saunas for 5.5 million people — nearly one per household.",
    neighbors: ["Sweden", "Norway", "Russia"],
  },
  {
    name: "Romania",
    code: "ro",
    flag: "\u{1F1F7}\u{1F1F4}",
    capital: "Bucharest",
    continent: "Europe",
    population: "19-20 million",
    funFact: "Home to Bran Castle, popularly associated with the legend of Count Dracula.",
    neighbors: ["Hungary", "Serbia", "Bulgaria", "Moldova", "Ukraine"],
  },
  {
    name: "Czech Republic",
    code: "cz",
    flag: "\u{1F1E8}\u{1F1FF}",
    capital: "Prague",
    continent: "Europe",
    population: "10-11 million",
    funFact: "Consumes the most beer per capita of any country in the world.",
    neighbors: ["Germany", "Poland", "Slovakia", "Austria"],
  },
  {
    name: "Denmark",
    code: "dk",
    flag: "\u{1F1E9}\u{1F1F0}",
    capital: "Copenhagen",
    continent: "Europe",
    population: "5-6 million",
    funFact: "LEGO was invented here — the name comes from the Danish phrase 'leg godt' meaning 'play well'.",
    neighbors: ["Germany", "Sweden", "Norway"],
  },

  // ── More Africa ────────────────────────────────────────────────────────────
  {
    name: "Tanzania",
    code: "tz",
    flag: "\u{1F1F9}\u{1F1FF}",
    capital: "Dodoma",
    continent: "Africa",
    population: "60-65 million",
    funFact: "Home to Mount Kilimanjaro, Africa's tallest peak at 5,895 meters.",
    neighbors: ["Kenya", "Uganda", "Rwanda", "Burundi", "Congo", "Zambia", "Malawi", "Mozambique"],
  },
  {
    name: "Senegal",
    code: "sn",
    flag: "\u{1F1F8}\u{1F1F3}",
    capital: "Dakar",
    continent: "Africa",
    population: "16-18 million",
    funFact: "Dakar was the finish line of the famous Paris-Dakar Rally for decades.",
    neighbors: ["Mauritania", "Mali", "Guinea", "Guinea-Bissau", "Gambia"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // AFRICA (continued)
  // ══════════════════════════════════════════════════════════════════════════

  {
    name: "Algeria",
    code: "dz",
    flag: "\u{1F1E9}\u{1F1FF}",
    capital: "Algiers",
    continent: "Africa",
    population: "44-46 million",
    funFact: "Is the largest country in Africa by land area.",
    neighbors: ["Morocco", "Tunisia", "Libya", "Niger", "Mali", "Mauritania"],
  },
  {
    name: "Angola",
    code: "ao",
    flag: "\u{1F1E6}\u{1F1F4}",
    capital: "Luanda",
    continent: "Africa",
    population: "33-36 million",
    funFact: "Is one of the world's top diamond-producing countries.",
    neighbors: ["Namibia", "Zambia", "Congo", "Republic of the Congo"],
  },
  {
    name: "Benin",
    code: "bj",
    flag: "\u{1F1E7}\u{1F1EF}",
    capital: "Porto-Novo",
    continent: "Africa",
    population: "12-14 million",
    funFact: "Is considered the birthplace of the Vodun (Voodoo) religion.",
    neighbors: ["Togo", "Burkina Faso", "Niger", "Nigeria"],
  },
  {
    name: "Botswana",
    code: "bw",
    flag: "\u{1F1E7}\u{1F1FC}",
    capital: "Gaborone",
    continent: "Africa",
    population: "2-3 million",
    funFact: "The Okavango Delta is the world's largest inland delta and a UNESCO World Heritage Site.",
    neighbors: ["Namibia", "South Africa", "Zimbabwe", "Zambia"],
  },
  {
    name: "Burkina Faso",
    code: "bf",
    flag: "\u{1F1E7}\u{1F1EB}",
    capital: "Ouagadougou",
    continent: "Africa",
    population: "21-23 million",
    funFact: "Its name means 'Land of Honest People' in the Mossi and Dyula languages.",
    neighbors: ["Mali", "Niger", "Benin", "Togo", "Ghana", "Ivory Coast"],
  },
  {
    name: "Burundi",
    code: "bi",
    flag: "\u{1F1E7}\u{1F1EE}",
    capital: "Gitega",
    continent: "Africa",
    population: "12-13 million",
    funFact: "Drumming is a sacred tradition and its Royal Drummers of Burundi are UNESCO-recognized.",
    neighbors: ["Rwanda", "Tanzania", "Congo"],
  },
  {
    name: "Cabo Verde",
    code: "cv",
    flag: "\u{1F1E8}\u{1F1FB}",
    capital: "Praia",
    continent: "Africa",
    population: "550-600 thousand",
    funFact: "This volcanic archipelago has more citizens living abroad than on the islands themselves.",
    neighbors: ["Senegal", "Gambia", "Mauritania"],
  },
  {
    name: "Cameroon",
    code: "cm",
    flag: "\u{1F1E8}\u{1F1F2}",
    capital: "Yaoundé",
    continent: "Africa",
    population: "26-28 million",
    funFact: "Is often called 'Africa in miniature' because of its geological and cultural diversity.",
    neighbors: ["Nigeria", "Chad", "Central African Republic", "Republic of the Congo", "Gabon", "Equatorial Guinea"],
  },
  {
    name: "Central African Republic",
    code: "cf",
    flag: "\u{1F1E8}\u{1F1EB}",
    capital: "Bangui",
    continent: "Africa",
    population: "5-6 million",
    funFact: "Home to some of the last remaining forest elephants in the Dzanga-Sangha Reserve.",
    neighbors: ["Chad", "Sudan", "South Sudan", "Congo", "Republic of the Congo", "Cameroon"],
  },
  {
    name: "Chad",
    code: "td",
    flag: "\u{1F1F9}\u{1F1E9}",
    capital: "N'Djamena",
    continent: "Africa",
    population: "16-18 million",
    funFact: "Lake Chad has shrunk by 90% since the 1960s due to climate change and water use.",
    neighbors: ["Libya", "Sudan", "Central African Republic", "Cameroon", "Nigeria", "Niger"],
  },
  {
    name: "Comoros",
    code: "km",
    flag: "\u{1F1F0}\u{1F1F2}",
    capital: "Moroni",
    continent: "Africa",
    population: "850-900 thousand",
    funFact: "Is one of the world's largest producers of ylang-ylang, used in perfumes.",
    neighbors: ["Madagascar", "Mozambique", "Tanzania"],
  },
  {
    name: "Congo",
    code: "cd",
    flag: "\u{1F1E8}\u{1F1E9}",
    capital: "Kinshasa",
    continent: "Africa",
    population: "95-105 million",
    funFact: "The Congo River is the deepest river in the world, reaching over 220 meters.",
    neighbors: ["Republic of the Congo", "Central African Republic", "South Sudan", "Uganda", "Rwanda", "Burundi", "Tanzania", "Zambia", "Angola"],
  },
  {
    name: "Republic of the Congo",
    code: "cg",
    flag: "\u{1F1E8}\u{1F1EC}",
    capital: "Brazzaville",
    continent: "Africa",
    population: "5-6 million",
    funFact: "Brazzaville and Kinshasa are the closest pair of capital cities in the world, separated only by the Congo River.",
    neighbors: ["Gabon", "Cameroon", "Central African Republic", "Congo", "Angola"],
  },
  {
    name: "Ivory Coast",
    code: "ci",
    flag: "\u{1F1E8}\u{1F1EE}",
    capital: "Yamoussoukro",
    continent: "Africa",
    population: "27-29 million",
    funFact: "Yamoussoukro has the world's largest church, the Basilica of Our Lady of Peace.",
    neighbors: ["Liberia", "Guinea", "Mali", "Burkina Faso", "Ghana"],
  },
  {
    name: "Djibouti",
    code: "dj",
    flag: "\u{1F1E9}\u{1F1EF}",
    capital: "Djibouti",
    continent: "Africa",
    population: "1-1.1 million",
    funFact: "Lake Assal is the lowest point in Africa and one of the saltiest bodies of water on Earth.",
    neighbors: ["Eritrea", "Ethiopia", "Somalia"],
  },
  {
    name: "Equatorial Guinea",
    code: "gq",
    flag: "\u{1F1EC}\u{1F1F6}",
    capital: "Malabo",
    continent: "Africa",
    population: "1.4-1.6 million",
    funFact: "Is the only country in Africa where Spanish is an official language.",
    neighbors: ["Cameroon", "Gabon"],
  },
  {
    name: "Eritrea",
    code: "er",
    flag: "\u{1F1EA}\u{1F1F7}",
    capital: "Asmara",
    continent: "Africa",
    population: "3-4 million",
    funFact: "Asmara is known as 'Little Rome' for its well-preserved Italian colonial architecture.",
    neighbors: ["Sudan", "Ethiopia", "Djibouti"],
  },
  {
    name: "Eswatini",
    code: "sz",
    flag: "\u{1F1F8}\u{1F1FF}",
    capital: "Mbabane",
    continent: "Africa",
    population: "1.1-1.2 million",
    funFact: "Is one of the last absolute monarchies in the world and changed its name from Swaziland in 2018.",
    neighbors: ["South Africa", "Mozambique"],
  },
  {
    name: "Gabon",
    code: "ga",
    flag: "\u{1F1EC}\u{1F1E6}",
    capital: "Libreville",
    continent: "Africa",
    population: "2-2.5 million",
    funFact: "About 80% of the country is covered by rainforest.",
    neighbors: ["Cameroon", "Equatorial Guinea", "Republic of the Congo"],
  },
  {
    name: "Gambia",
    code: "gm",
    flag: "\u{1F1EC}\u{1F1F2}",
    capital: "Banjul",
    continent: "Africa",
    population: "2.4-2.7 million",
    funFact: "Is the smallest country on mainland Africa and is almost entirely surrounded by Senegal.",
    neighbors: ["Senegal"],
  },
  {
    name: "Guinea",
    code: "gn",
    flag: "\u{1F1EC}\u{1F1F3}",
    capital: "Conakry",
    continent: "Africa",
    population: "13-14 million",
    funFact: "Holds more than a quarter of the world's known bauxite reserves.",
    neighbors: ["Guinea-Bissau", "Senegal", "Mali", "Ivory Coast", "Liberia", "Sierra Leone"],
  },
  {
    name: "Guinea-Bissau",
    code: "gw",
    flag: "\u{1F1EC}\u{1F1FC}",
    capital: "Bissau",
    continent: "Africa",
    population: "2-2.2 million",
    funFact: "The Bijagos Archipelago is one of the few places where saltwater hippos can be found.",
    neighbors: ["Senegal", "Guinea"],
  },
  {
    name: "Lesotho",
    code: "ls",
    flag: "\u{1F1F1}\u{1F1F8}",
    capital: "Maseru",
    continent: "Africa",
    population: "2-2.2 million",
    funFact: "Is the only country in the world where every point is above 1,000 meters elevation.",
    neighbors: ["South Africa"],
  },
  {
    name: "Liberia",
    code: "lr",
    flag: "\u{1F1F1}\u{1F1F7}",
    capital: "Monrovia",
    continent: "Africa",
    population: "5-5.5 million",
    funFact: "Was founded by freed American slaves and its capital is named after US President James Monroe.",
    neighbors: ["Sierra Leone", "Guinea", "Ivory Coast"],
  },
  {
    name: "Libya",
    code: "ly",
    flag: "\u{1F1F1}\u{1F1FE}",
    capital: "Tripoli",
    continent: "Africa",
    population: "7-8 million",
    funFact: "About 90% of the country is desert, making it one of the sunniest places on Earth.",
    neighbors: ["Tunisia", "Algeria", "Niger", "Chad", "Sudan", "Egypt"],
  },
  {
    name: "Malawi",
    code: "mw",
    flag: "\u{1F1F2}\u{1F1FC}",
    capital: "Lilongwe",
    continent: "Africa",
    population: "19-21 million",
    funFact: "Lake Malawi contains more fish species than any other lake in the world.",
    neighbors: ["Tanzania", "Mozambique", "Zambia"],
  },
  {
    name: "Mali",
    code: "ml",
    flag: "\u{1F1F2}\u{1F1F1}",
    capital: "Bamako",
    continent: "Africa",
    population: "20-22 million",
    funFact: "Timbuktu was once one of the world's great centers of learning and had a famous medieval university.",
    neighbors: ["Algeria", "Niger", "Burkina Faso", "Ivory Coast", "Guinea", "Senegal", "Mauritania"],
  },
  {
    name: "Mauritania",
    code: "mr",
    flag: "\u{1F1F2}\u{1F1F7}",
    capital: "Nouakchott",
    continent: "Africa",
    population: "4-5 million",
    funFact: "The Richat Structure, known as the 'Eye of the Sahara', is a massive circular geological formation visible from space.",
    neighbors: ["Morocco", "Algeria", "Mali", "Senegal"],
  },
  {
    name: "Mauritius",
    code: "mu",
    flag: "\u{1F1F2}\u{1F1FA}",
    capital: "Port Louis",
    continent: "Africa",
    population: "1.2-1.3 million",
    funFact: "Was the only known home of the dodo bird, which went extinct in the 17th century.",
    neighbors: ["Madagascar", "Réunion"],
  },
  {
    name: "Mozambique",
    code: "mz",
    flag: "\u{1F1F2}\u{1F1FF}",
    capital: "Maputo",
    continent: "Africa",
    population: "31-33 million",
    funFact: "Is the only country in the world with an AK-47 on its national flag.",
    neighbors: ["Tanzania", "Malawi", "Zambia", "Zimbabwe", "South Africa", "Eswatini"],
  },
  {
    name: "Namibia",
    code: "na",
    flag: "\u{1F1F3}\u{1F1E6}",
    capital: "Windhoek",
    continent: "Africa",
    population: "2.5-3 million",
    funFact: "The Namib Desert is considered the oldest desert in the world at roughly 55 million years old.",
    neighbors: ["Angola", "Zambia", "Botswana", "South Africa"],
  },
  {
    name: "Niger",
    code: "ne",
    flag: "\u{1F1F3}\u{1F1EA}",
    capital: "Niamey",
    continent: "Africa",
    population: "24-26 million",
    funFact: "Has the youngest population in the world, with a median age of about 15 years.",
    neighbors: ["Algeria", "Libya", "Chad", "Nigeria", "Benin", "Burkina Faso", "Mali"],
  },
  {
    name: "Rwanda",
    code: "rw",
    flag: "\u{1F1F7}\u{1F1FC}",
    capital: "Kigali",
    continent: "Africa",
    population: "13-14 million",
    funFact: "Has the highest percentage of women in parliament of any country in the world.",
    neighbors: ["Uganda", "Tanzania", "Burundi", "Congo"],
  },
  {
    name: "São Tomé and Príncipe",
    code: "st",
    flag: "\u{1F1F8}\u{1F1F9}",
    capital: "São Tomé",
    continent: "Africa",
    population: "200-220 thousand",
    funFact: "Is the smallest Portuguese-speaking country in the world.",
    neighbors: ["Gabon", "Equatorial Guinea"],
  },
  {
    name: "Sierra Leone",
    code: "sl",
    flag: "\u{1F1F8}\u{1F1F1}",
    capital: "Freetown",
    continent: "Africa",
    population: "8-9 million",
    funFact: "Freetown was founded as a home for freed slaves, giving the capital its name.",
    neighbors: ["Guinea", "Liberia"],
  },
  {
    name: "Somalia",
    code: "so",
    flag: "\u{1F1F8}\u{1F1F4}",
    capital: "Mogadishu",
    continent: "Africa",
    population: "16-18 million",
    funFact: "Has the longest coastline on mainland Africa, stretching about 3,025 km.",
    neighbors: ["Djibouti", "Ethiopia", "Kenya"],
  },
  {
    name: "South Sudan",
    code: "ss",
    flag: "\u{1F1F8}\u{1F1F8}",
    capital: "Juba",
    continent: "Africa",
    population: "11-12 million",
    funFact: "Became the world's newest country when it gained independence in 2011.",
    neighbors: ["Sudan", "Ethiopia", "Kenya", "Uganda", "Congo", "Central African Republic"],
  },
  {
    name: "Sudan",
    code: "sd",
    flag: "\u{1F1F8}\u{1F1E9}",
    capital: "Khartoum",
    continent: "Africa",
    population: "44-46 million",
    funFact: "Has more pyramids than Egypt — over 200 ancient Nubian pyramids.",
    neighbors: ["Egypt", "Libya", "Chad", "Central African Republic", "South Sudan", "Ethiopia", "Eritrea"],
  },
  {
    name: "Togo",
    code: "tg",
    flag: "\u{1F1F9}\u{1F1EC}",
    capital: "Lomé",
    continent: "Africa",
    population: "8-9 million",
    funFact: "Is one of the narrowest countries in the world, only about 115 km wide.",
    neighbors: ["Ghana", "Benin", "Burkina Faso"],
  },
  {
    name: "Tunisia",
    code: "tn",
    flag: "\u{1F1F9}\u{1F1F3}",
    capital: "Tunis",
    continent: "Africa",
    population: "12-13 million",
    funFact: "Contains the ruins of ancient Carthage, once Rome's greatest rival.",
    neighbors: ["Algeria", "Libya"],
  },
  {
    name: "Uganda",
    code: "ug",
    flag: "\u{1F1FA}\u{1F1EC}",
    capital: "Kampala",
    continent: "Africa",
    population: "45-48 million",
    funFact: "Is home to more than half of the world's remaining mountain gorillas.",
    neighbors: ["Kenya", "Tanzania", "Rwanda", "Congo", "South Sudan"],
  },
  {
    name: "Zambia",
    code: "zm",
    flag: "\u{1F1FF}\u{1F1F2}",
    capital: "Lusaka",
    continent: "Africa",
    population: "18-20 million",
    funFact: "Victoria Falls on the Zambia-Zimbabwe border is one of the largest waterfalls in the world.",
    neighbors: ["Congo", "Tanzania", "Malawi", "Mozambique", "Zimbabwe", "Botswana", "Namibia", "Angola"],
  },
  {
    name: "Zimbabwe",
    code: "zw",
    flag: "\u{1F1FF}\u{1F1FC}",
    capital: "Harare",
    continent: "Africa",
    population: "15-16 million",
    funFact: "The Great Zimbabwe ruins are among the oldest and largest structures in southern Africa.",
    neighbors: ["Zambia", "Mozambique", "South Africa", "Botswana"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ASIA
  // ══════════════════════════════════════════════════════════════════════════

  {
    name: "Afghanistan",
    code: "af",
    flag: "\u{1F1E6}\u{1F1EB}",
    capital: "Kabul",
    continent: "Asia",
    population: "40-42 million",
    funFact: "Is home to the ancient Buddhas of Bamiyan valley, a UNESCO heritage site.",
    neighbors: ["Pakistan", "Iran", "Turkmenistan", "Uzbekistan", "Tajikistan", "China"],
  },
  {
    name: "Armenia",
    code: "am",
    flag: "\u{1F1E6}\u{1F1F2}",
    capital: "Yerevan",
    continent: "Asia",
    population: "2.8-3 million",
    funFact: "Was the first country in the world to adopt Christianity as its state religion in 301 AD.",
    neighbors: ["Georgia", "Azerbaijan", "Iran", "Turkey"],
  },
  {
    name: "Azerbaijan",
    code: "az",
    flag: "\u{1F1E6}\u{1F1FF}",
    capital: "Baku",
    continent: "Asia",
    population: "10-11 million",
    funFact: "Known as the 'Land of Fire' because of natural gas fires that have burned on hillsides for millennia.",
    neighbors: ["Russia", "Georgia", "Armenia", "Iran"],
  },
  {
    name: "Bahrain",
    code: "bh",
    flag: "\u{1F1E7}\u{1F1ED}",
    capital: "Manama",
    continent: "Asia",
    population: "1.5-1.7 million",
    funFact: "Is an archipelago of 33 islands and was the first Gulf state to discover oil.",
    neighbors: ["Saudi Arabia", "Qatar"],
  },
  {
    name: "Bhutan",
    code: "bt",
    flag: "\u{1F1E7}\u{1F1F9}",
    capital: "Thimphu",
    continent: "Asia",
    population: "750-800 thousand",
    funFact: "Measures national success by Gross National Happiness instead of GDP.",
    neighbors: ["India", "China"],
  },
  {
    name: "Brunei",
    code: "bn",
    flag: "\u{1F1E7}\u{1F1F3}",
    capital: "Bandar Seri Begawan",
    continent: "Asia",
    population: "440-460 thousand",
    funFact: "The Sultan of Brunei's palace is the largest residential palace in the world with 1,788 rooms.",
    neighbors: ["Malaysia"],
  },
  {
    name: "Cambodia",
    code: "kh",
    flag: "\u{1F1F0}\u{1F1ED}",
    capital: "Phnom Penh",
    continent: "Asia",
    population: "16-17 million",
    funFact: "Angkor Wat is the largest religious monument in the world.",
    neighbors: ["Thailand", "Laos", "Vietnam"],
  },
  {
    name: "China",
    code: "cn",
    flag: "\u{1F1E8}\u{1F1F3}",
    capital: "Beijing",
    continent: "Asia",
    population: "1.4-1.45 billion",
    funFact: "The Great Wall of China stretches over 21,000 km and took more than 2,000 years to build.",
    neighbors: ["Russia", "Mongolia", "North Korea", "Vietnam", "Laos", "Myanmar", "India", "Bhutan", "Nepal", "Pakistan", "Afghanistan", "Tajikistan", "Kyrgyzstan", "Kazakhstan"],
  },
  {
    name: "Cyprus",
    code: "cy",
    flag: "\u{1F1E8}\u{1F1FE}",
    capital: "Nicosia",
    continent: "Asia",
    population: "1.2-1.3 million",
    funFact: "Nicosia is the last divided capital city in the world.",
    neighbors: ["Turkey", "Greece", "Syria"],
  },
  {
    name: "Georgia",
    code: "ge",
    flag: "\u{1F1EC}\u{1F1EA}",
    capital: "Tbilisi",
    continent: "Asia",
    population: "3.7-4 million",
    funFact: "Is one of the oldest wine-producing regions in the world, with 8,000 years of viticulture.",
    neighbors: ["Russia", "Turkey", "Armenia", "Azerbaijan"],
  },
  {
    name: "Iran",
    code: "ir",
    flag: "\u{1F1EE}\u{1F1F7}",
    capital: "Tehran",
    continent: "Asia",
    population: "85-88 million",
    funFact: "Has one of the oldest continuous civilizations, dating back to 3200 BC.",
    neighbors: ["Iraq", "Turkey", "Armenia", "Azerbaijan", "Turkmenistan", "Afghanistan", "Pakistan"],
  },
  {
    name: "Iraq",
    code: "iq",
    flag: "\u{1F1EE}\u{1F1F6}",
    capital: "Baghdad",
    continent: "Asia",
    population: "41-43 million",
    funFact: "Ancient Mesopotamia, the 'Cradle of Civilization', was located in modern-day Iraq.",
    neighbors: ["Turkey", "Iran", "Kuwait", "Saudi Arabia", "Jordan", "Syria"],
  },
  {
    name: "Jordan",
    code: "jo",
    flag: "\u{1F1EF}\u{1F1F4}",
    capital: "Amman",
    continent: "Asia",
    population: "10-11 million",
    funFact: "Petra, the ancient city carved into rose-red cliffs, is one of the New Seven Wonders of the World.",
    neighbors: ["Syria", "Iraq", "Saudi Arabia", "Israel", "Palestine"],
  },
  {
    name: "Kazakhstan",
    code: "kz",
    flag: "\u{1F1F0}\u{1F1FF}",
    capital: "Astana",
    continent: "Asia",
    population: "19-20 million",
    funFact: "Is the largest landlocked country in the world and the ninth-largest country overall.",
    neighbors: ["Russia", "China", "Kyrgyzstan", "Uzbekistan", "Turkmenistan"],
  },
  {
    name: "Kuwait",
    code: "kw",
    flag: "\u{1F1F0}\u{1F1FC}",
    capital: "Kuwait City",
    continent: "Asia",
    population: "4.2-4.5 million",
    funFact: "Has roughly 10% of the world's proven oil reserves despite its small size.",
    neighbors: ["Iraq", "Saudi Arabia"],
  },
  {
    name: "Kyrgyzstan",
    code: "kg",
    flag: "\u{1F1F0}\u{1F1EC}",
    capital: "Bishkek",
    continent: "Asia",
    population: "6.5-7 million",
    funFact: "Is home to Issyk-Kul, one of the largest alpine lakes in the world.",
    neighbors: ["Kazakhstan", "Uzbekistan", "Tajikistan", "China"],
  },
  {
    name: "Laos",
    code: "la",
    flag: "\u{1F1F1}\u{1F1E6}",
    capital: "Vientiane",
    continent: "Asia",
    population: "7-8 million",
    funFact: "Is the most heavily bombed country per capita in history, due to the Vietnam War era.",
    neighbors: ["Myanmar", "China", "Vietnam", "Cambodia", "Thailand"],
  },
  {
    name: "Lebanon",
    code: "lb",
    flag: "\u{1F1F1}\u{1F1E7}",
    capital: "Beirut",
    continent: "Asia",
    population: "5-6 million",
    funFact: "The ancient city of Byblos is one of the oldest continuously inhabited cities in the world.",
    neighbors: ["Syria", "Israel"],
  },
  {
    name: "Malaysia",
    code: "my",
    flag: "\u{1F1F2}\u{1F1FE}",
    capital: "Kuala Lumpur",
    continent: "Asia",
    population: "32-34 million",
    funFact: "The Petronas Twin Towers were the tallest buildings in the world from 1998 to 2004.",
    neighbors: ["Thailand", "Indonesia", "Brunei", "Singapore", "Philippines"],
  },
  {
    name: "Maldives",
    code: "mv",
    flag: "\u{1F1F2}\u{1F1FB}",
    capital: "Malé",
    continent: "Asia",
    population: "500-550 thousand",
    funFact: "Is the lowest-lying country in the world with an average elevation of just 1.5 meters above sea level.",
    neighbors: ["Sri Lanka", "India"],
  },
  {
    name: "Myanmar",
    code: "mm",
    flag: "\u{1F1F2}\u{1F1F2}",
    capital: "Naypyidaw",
    continent: "Asia",
    population: "54-56 million",
    funFact: "Is one of only three countries in the world that has not officially adopted the metric system.",
    neighbors: ["India", "Bangladesh", "China", "Laos", "Thailand"],
  },
  {
    name: "North Korea",
    code: "kp",
    flag: "\u{1F1F0}\u{1F1F5}",
    capital: "Pyongyang",
    continent: "Asia",
    population: "25-26 million",
    funFact: "Has its own calendar system called the Juche calendar, starting from 1912.",
    neighbors: ["South Korea", "China", "Russia"],
  },
  {
    name: "Oman",
    code: "om",
    flag: "\u{1F1F4}\u{1F1F2}",
    capital: "Muscat",
    continent: "Asia",
    population: "5-5.5 million",
    funFact: "Has some of the oldest human settlements in the Arabian Peninsula, dating back 10,000 years.",
    neighbors: ["Yemen", "Saudi Arabia", "UAE"],
  },
  {
    name: "Qatar",
    code: "qa",
    flag: "\u{1F1F6}\u{1F1E6}",
    capital: "Doha",
    continent: "Asia",
    population: "2.8-3 million",
    funFact: "Has the highest GDP per capita in the world, largely from natural gas exports.",
    neighbors: ["Saudi Arabia", "Bahrain", "UAE"],
  },
  {
    name: "Singapore",
    code: "sg",
    flag: "\u{1F1F8}\u{1F1EC}",
    capital: "Singapore",
    continent: "Asia",
    population: "5.5-6 million",
    funFact: "Is both a city and a country, and has the world's first night-time zoo.",
    neighbors: ["Malaysia", "Indonesia"],
  },
  {
    name: "Syria",
    code: "sy",
    flag: "\u{1F1F8}\u{1F1FE}",
    capital: "Damascus",
    continent: "Asia",
    population: "21-23 million",
    funFact: "Damascus is one of the oldest continuously inhabited cities in the world, with over 11,000 years of history.",
    neighbors: ["Turkey", "Iraq", "Jordan", "Israel", "Lebanon"],
  },
  {
    name: "Tajikistan",
    code: "tj",
    flag: "\u{1F1F9}\u{1F1EF}",
    capital: "Dushanbe",
    continent: "Asia",
    population: "9.5-10 million",
    funFact: "Over 90% of the country is mountainous, with many peaks above 7,000 meters.",
    neighbors: ["Kyrgyzstan", "Uzbekistan", "Afghanistan", "China"],
  },
  {
    name: "Turkmenistan",
    code: "tm",
    flag: "\u{1F1F9}\u{1F1F2}",
    capital: "Ashgabat",
    continent: "Asia",
    population: "6-6.5 million",
    funFact: "The Darvaza Gas Crater, known as the 'Door to Hell', has been burning since 1971.",
    neighbors: ["Kazakhstan", "Uzbekistan", "Afghanistan", "Iran"],
  },
  {
    name: "United Arab Emirates",
    code: "ae",
    flag: "\u{1F1E6}\u{1F1EA}",
    capital: "Abu Dhabi",
    continent: "Asia",
    population: "9-10 million",
    funFact: "Dubai's Burj Khalifa is the tallest building in the world at 828 meters.",
    neighbors: ["Saudi Arabia", "Oman"],
  },
  {
    name: "Uzbekistan",
    code: "uz",
    flag: "\u{1F1FA}\u{1F1FF}",
    capital: "Tashkent",
    continent: "Asia",
    population: "34-36 million",
    funFact: "Samarkand was a key stop on the ancient Silk Road and has stunning Islamic architecture.",
    neighbors: ["Kazakhstan", "Kyrgyzstan", "Tajikistan", "Afghanistan", "Turkmenistan"],
  },
  {
    name: "Yemen",
    code: "ye",
    flag: "\u{1F1FE}\u{1F1EA}",
    capital: "Sana'a",
    continent: "Asia",
    population: "30-33 million",
    funFact: "The island of Socotra has plant species found nowhere else on Earth, earning it the nickname 'Galapagos of the Indian Ocean'.",
    neighbors: ["Saudi Arabia", "Oman"],
  },
  {
    name: "East Timor",
    code: "tl",
    flag: "\u{1F1F9}\u{1F1F1}",
    capital: "Dili",
    continent: "Asia",
    population: "1.3-1.4 million",
    funFact: "Became the first new sovereign state of the 21st century when it gained independence in 2002.",
    neighbors: ["Indonesia", "Australia"],
  },
  {
    name: "Palestine",
    code: "ps",
    flag: "\u{1F1F5}\u{1F1F8}",
    capital: "Ramallah",
    continent: "Asia",
    population: "5-5.5 million",
    funFact: "Jericho, in the West Bank, is one of the oldest continuously inhabited cities in the world.",
    neighbors: ["Israel", "Egypt", "Jordan"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // EUROPE
  // ══════════════════════════════════════════════════════════════════════════

  {
    name: "Albania",
    code: "al",
    flag: "\u{1F1E6}\u{1F1F1}",
    capital: "Tirana",
    continent: "Europe",
    population: "2.8-3 million",
    funFact: "Has over 750,000 bunkers built during the communist era — more bunkers per capita than any other country.",
    neighbors: ["Montenegro", "Kosovo", "North Macedonia", "Greece"],
  },
  {
    name: "Andorra",
    code: "ad",
    flag: "\u{1F1E6}\u{1F1E9}",
    capital: "Andorra la Vella",
    continent: "Europe",
    population: "77-80 thousand",
    funFact: "Has the highest capital city in Europe at 1,023 meters above sea level.",
    neighbors: ["France", "Spain"],
  },
  {
    name: "Austria",
    code: "at",
    flag: "\u{1F1E6}\u{1F1F9}",
    capital: "Vienna",
    continent: "Europe",
    population: "9-9.5 million",
    funFact: "Vienna has been ranked the world's most liveable city multiple times.",
    neighbors: ["Germany", "Czech Republic", "Slovakia", "Hungary", "Slovenia", "Italy", "Switzerland", "Liechtenstein"],
  },
  {
    name: "Belarus",
    code: "by",
    flag: "\u{1F1E7}\u{1F1FE}",
    capital: "Minsk",
    continent: "Europe",
    population: "9-10 million",
    funFact: "Has Europe's largest remaining primeval forest, Belovezhskaya Pushcha, home to European bison.",
    neighbors: ["Russia", "Ukraine", "Poland", "Lithuania", "Latvia"],
  },
  {
    name: "Belgium",
    code: "be",
    flag: "\u{1F1E7}\u{1F1EA}",
    capital: "Brussels",
    continent: "Europe",
    population: "11-12 million",
    funFact: "Produces over 220,000 tonnes of chocolate per year and Brussels is the de facto capital of the EU.",
    neighbors: ["Netherlands", "Germany", "Luxembourg", "France"],
  },
  {
    name: "Bosnia and Herzegovina",
    code: "ba",
    flag: "\u{1F1E7}\u{1F1E6}",
    capital: "Sarajevo",
    continent: "Europe",
    population: "3.2-3.5 million",
    funFact: "Sarajevo hosted the 1984 Winter Olympics and has a famous historic old bazaar, Bascarsija.",
    neighbors: ["Croatia", "Serbia", "Montenegro"],
  },
  {
    name: "Bulgaria",
    code: "bg",
    flag: "\u{1F1E7}\u{1F1EC}",
    capital: "Sofia",
    continent: "Europe",
    population: "6.5-7 million",
    funFact: "Bulgarians shake their head to mean 'yes' and nod to mean 'no'.",
    neighbors: ["Romania", "Serbia", "North Macedonia", "Greece", "Turkey"],
  },
  {
    name: "Estonia",
    code: "ee",
    flag: "\u{1F1EA}\u{1F1EA}",
    capital: "Tallinn",
    continent: "Europe",
    population: "1.3-1.4 million",
    funFact: "Was the first country to offer e-residency and holds national elections online.",
    neighbors: ["Latvia", "Russia"],
  },
  {
    name: "Hungary",
    code: "hu",
    flag: "\u{1F1ED}\u{1F1FA}",
    capital: "Budapest",
    continent: "Europe",
    population: "9.5-10 million",
    funFact: "Budapest has the largest thermal water cave system in Europe.",
    neighbors: ["Austria", "Slovakia", "Ukraine", "Romania", "Serbia", "Croatia", "Slovenia"],
  },
  {
    name: "Kosovo",
    code: "xk",
    flag: "\u{1F1FD}\u{1F1F0}",
    capital: "Pristina",
    continent: "Europe",
    population: "1.8-2 million",
    funFact: "Declared independence in 2008 and is one of the youngest countries in Europe.",
    neighbors: ["Serbia", "North Macedonia", "Albania", "Montenegro"],
  },
  {
    name: "Latvia",
    code: "lv",
    flag: "\u{1F1F1}\u{1F1FB}",
    capital: "Riga",
    continent: "Europe",
    population: "1.8-2 million",
    funFact: "Riga has the largest collection of Art Nouveau architecture in the world.",
    neighbors: ["Estonia", "Lithuania", "Russia", "Belarus"],
  },
  {
    name: "Liechtenstein",
    code: "li",
    flag: "\u{1F1F1}\u{1F1EE}",
    capital: "Vaduz",
    continent: "Europe",
    population: "38-40 thousand",
    funFact: "Is one of only two doubly landlocked countries in the world.",
    neighbors: ["Switzerland", "Austria"],
  },
  {
    name: "Lithuania",
    code: "lt",
    flag: "\u{1F1F1}\u{1F1F9}",
    capital: "Vilnius",
    continent: "Europe",
    population: "2.7-2.9 million",
    funFact: "Has the geographic center of Europe near its capital city Vilnius.",
    neighbors: ["Latvia", "Belarus", "Poland", "Russia"],
  },
  {
    name: "Luxembourg",
    code: "lu",
    flag: "\u{1F1F1}\u{1F1FA}",
    capital: "Luxembourg City",
    continent: "Europe",
    population: "640-660 thousand",
    funFact: "Has the highest GDP per capita in the world and three official languages.",
    neighbors: ["Belgium", "Germany", "France"],
  },
  {
    name: "Malta",
    code: "mt",
    flag: "\u{1F1F2}\u{1F1F9}",
    capital: "Valletta",
    continent: "Europe",
    population: "500-520 thousand",
    funFact: "Valletta is the smallest national capital in the EU and the Megalithic Temples are older than the pyramids.",
    neighbors: ["Italy", "Tunisia"],
  },
  {
    name: "Moldova",
    code: "md",
    flag: "\u{1F1F2}\u{1F1E9}",
    capital: "Chișinău",
    continent: "Europe",
    population: "2.5-3 million",
    funFact: "Has the world's largest wine cellar, Mileștii Mici, with over 200 km of underground tunnels.",
    neighbors: ["Romania", "Ukraine"],
  },
  {
    name: "Monaco",
    code: "mc",
    flag: "\u{1F1F2}\u{1F1E8}",
    capital: "Monaco",
    continent: "Europe",
    population: "38-40 thousand",
    funFact: "Is the most densely populated country in the world and hosts the famous Formula 1 Grand Prix.",
    neighbors: ["France"],
  },
  {
    name: "Montenegro",
    code: "me",
    flag: "\u{1F1F2}\u{1F1EA}",
    capital: "Podgorica",
    continent: "Europe",
    population: "620-640 thousand",
    funFact: "Has one of the deepest canyons in the world — the Tara River Canyon at 1,300 meters deep.",
    neighbors: ["Croatia", "Bosnia and Herzegovina", "Serbia", "Kosovo", "Albania"],
  },
  {
    name: "Netherlands",
    code: "nl",
    flag: "\u{1F1F3}\u{1F1F1}",
    capital: "Amsterdam",
    continent: "Europe",
    population: "17-18 million",
    funFact: "About one third of the country lies below sea level, protected by an extensive system of dikes.",
    neighbors: ["Belgium", "Germany"],
  },
  {
    name: "North Macedonia",
    code: "mk",
    flag: "\u{1F1F2}\u{1F1F0}",
    capital: "Skopje",
    continent: "Europe",
    population: "2-2.1 million",
    funFact: "Lake Ohrid is one of the oldest and deepest lakes in Europe, home to unique species.",
    neighbors: ["Kosovo", "Serbia", "Bulgaria", "Greece", "Albania"],
  },
  {
    name: "Russia",
    code: "ru",
    flag: "\u{1F1F7}\u{1F1FA}",
    capital: "Moscow",
    continent: "Europe",
    population: "144-146 million",
    funFact: "Spans 11 time zones, making it the widest country in the world.",
    neighbors: ["Norway", "Finland", "Estonia", "Latvia", "Lithuania", "Poland", "Belarus", "Ukraine", "Georgia", "Azerbaijan", "Kazakhstan", "China", "Mongolia", "North Korea"],
  },
  {
    name: "San Marino",
    code: "sm",
    flag: "\u{1F1F8}\u{1F1F2}",
    capital: "San Marino",
    continent: "Europe",
    population: "33-34 thousand",
    funFact: "Claims to be the oldest republic in the world, founded in 301 AD.",
    neighbors: ["Italy"],
  },
  {
    name: "Serbia",
    code: "rs",
    flag: "\u{1F1F7}\u{1F1F8}",
    capital: "Belgrade",
    continent: "Europe",
    population: "6.5-7 million",
    funFact: "Belgrade is one of the oldest continuously inhabited cities in Europe, dating back over 7,000 years.",
    neighbors: ["Hungary", "Romania", "Bulgaria", "North Macedonia", "Kosovo", "Montenegro", "Bosnia and Herzegovina", "Croatia"],
  },
  {
    name: "Slovakia",
    code: "sk",
    flag: "\u{1F1F8}\u{1F1F0}",
    capital: "Bratislava",
    continent: "Europe",
    population: "5.4-5.5 million",
    funFact: "Has more castles and chateaux per capita than any other country in the world.",
    neighbors: ["Czech Republic", "Poland", "Ukraine", "Hungary", "Austria"],
  },
  {
    name: "Slovenia",
    code: "si",
    flag: "\u{1F1F8}\u{1F1EE}",
    capital: "Ljubljana",
    continent: "Europe",
    population: "2.1-2.2 million",
    funFact: "Over 60% of the country is covered by forest and it has the word 'love' in its name.",
    neighbors: ["Italy", "Austria", "Hungary", "Croatia"],
  },
  {
    name: "Ukraine",
    code: "ua",
    flag: "\u{1F1FA}\u{1F1E6}",
    capital: "Kyiv",
    continent: "Europe",
    population: "43-44 million",
    funFact: "Has one of the deepest metro stations in the world — Arsenalna in Kyiv at 105.5 meters below ground.",
    neighbors: ["Russia", "Belarus", "Poland", "Slovakia", "Hungary", "Romania", "Moldova"],
  },
  {
    name: "United Kingdom",
    code: "gb",
    flag: "\u{1F1EC}\u{1F1E7}",
    capital: "London",
    continent: "Europe",
    population: "67-68 million",
    funFact: "The London Underground is the oldest underground railway network in the world, opened in 1863.",
    neighbors: ["Ireland", "France", "Belgium", "Netherlands"],
  },
  {
    name: "Vatican City",
    code: "va",
    flag: "\u{1F1FB}\u{1F1E6}",
    capital: "Vatican City",
    continent: "Europe",
    population: "800-900",
    funFact: "Is the smallest country in the world at just 0.44 square kilometers.",
    neighbors: ["Italy"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NORTH AMERICA (Central America & Caribbean)
  // ══════════════════════════════════════════════════════════════════════════

  {
    name: "United States",
    code: "us",
    flag: "\u{1F1FA}\u{1F1F8}",
    capital: "Washington, D.C.",
    continent: "North America",
    population: "330-335 million",
    funFact: "Has the world's oldest written constitution still in use, ratified in 1788.",
    neighbors: ["Canada", "Mexico"],
  },
  {
    name: "Antigua and Barbuda",
    code: "ag",
    flag: "\u{1F1E6}\u{1F1EC}",
    capital: "St. John's",
    continent: "North America",
    population: "95-100 thousand",
    funFact: "Claims to have a different beach for every day of the year — 365 beaches in all.",
    neighbors: ["Saint Kitts and Nevis", "Dominica"],
  },
  {
    name: "Bahamas",
    code: "bs",
    flag: "\u{1F1E7}\u{1F1F8}",
    capital: "Nassau",
    continent: "North America",
    population: "400-420 thousand",
    funFact: "Dean's Blue Hole is the world's second-deepest known saltwater blue hole at over 200 meters.",
    neighbors: ["United States", "Cuba"],
  },
  {
    name: "Barbados",
    code: "bb",
    flag: "\u{1F1E7}\u{1F1E7}",
    capital: "Bridgetown",
    continent: "North America",
    population: "280-290 thousand",
    funFact: "Is the birthplace of rum and has one of the oldest parliaments in the Western Hemisphere.",
    neighbors: ["Saint Vincent and the Grenadines", "Saint Lucia", "Trinidad and Tobago"],
  },
  {
    name: "Belize",
    code: "bz",
    flag: "\u{1F1E7}\u{1F1FF}",
    capital: "Belmopan",
    continent: "North America",
    population: "400-430 thousand",
    funFact: "Has the largest barrier reef in the Western Hemisphere and the famous Great Blue Hole.",
    neighbors: ["Mexico", "Guatemala"],
  },
  {
    name: "Dominica",
    code: "dm",
    flag: "\u{1F1E9}\u{1F1F2}",
    capital: "Roseau",
    continent: "North America",
    population: "72-75 thousand",
    funFact: "Known as the 'Nature Isle of the Caribbean' and has the world's second-largest hot spring, Boiling Lake.",
    neighbors: ["Guadeloupe", "Martinique"],
  },
  {
    name: "Dominican Republic",
    code: "do",
    flag: "\u{1F1E9}\u{1F1F4}",
    capital: "Santo Domingo",
    continent: "North America",
    population: "10-11 million",
    funFact: "Santo Domingo was the first permanent European settlement in the Americas.",
    neighbors: ["Haiti"],
  },
  {
    name: "El Salvador",
    code: "sv",
    flag: "\u{1F1F8}\u{1F1FB}",
    capital: "San Salvador",
    continent: "North America",
    population: "6.5-7 million",
    funFact: "Was the first country to adopt Bitcoin as legal tender in 2021.",
    neighbors: ["Guatemala", "Honduras"],
  },
  {
    name: "Grenada",
    code: "gd",
    flag: "\u{1F1EC}\u{1F1E9}",
    capital: "St. George's",
    continent: "North America",
    population: "112-115 thousand",
    funFact: "Known as the 'Spice Isle' because it produces about 20% of the world's nutmeg.",
    neighbors: ["Trinidad and Tobago", "Saint Vincent and the Grenadines"],
  },
  {
    name: "Haiti",
    code: "ht",
    flag: "\u{1F1ED}\u{1F1F9}",
    capital: "Port-au-Prince",
    continent: "North America",
    population: "11-12 million",
    funFact: "Was the first independent nation in Latin America and the first Black-led republic in the world.",
    neighbors: ["Dominican Republic", "Cuba", "Jamaica"],
  },
  {
    name: "Honduras",
    code: "hn",
    flag: "\u{1F1ED}\u{1F1F3}",
    capital: "Tegucigalpa",
    continent: "North America",
    population: "10-11 million",
    funFact: "The ancient Maya city of Copan is one of the most important archaeological sites in the Americas.",
    neighbors: ["Guatemala", "El Salvador", "Nicaragua"],
  },
  {
    name: "Nicaragua",
    code: "ni",
    flag: "\u{1F1F3}\u{1F1EE}",
    capital: "Managua",
    continent: "North America",
    population: "6.5-7 million",
    funFact: "Lake Nicaragua is one of the few freshwater lakes in the world that has bull sharks.",
    neighbors: ["Honduras", "Costa Rica"],
  },
  {
    name: "Saint Kitts and Nevis",
    code: "kn",
    flag: "\u{1F1F0}\u{1F1F3}",
    capital: "Basseterre",
    continent: "North America",
    population: "53-55 thousand",
    funFact: "Is the smallest sovereign state in the Americas by both area and population.",
    neighbors: ["Antigua and Barbuda", "Netherlands"],
  },
  {
    name: "Saint Lucia",
    code: "lc",
    flag: "\u{1F1F1}\u{1F1E8}",
    capital: "Castries",
    continent: "North America",
    population: "180-185 thousand",
    funFact: "Has the world's only drive-in volcano at Soufriere.",
    neighbors: ["Martinique", "Saint Vincent and the Grenadines", "Barbados"],
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "vc",
    flag: "\u{1F1FB}\u{1F1E8}",
    capital: "Kingstown",
    continent: "North America",
    population: "110-115 thousand",
    funFact: "Parts of the Pirates of the Caribbean movies were filmed on its islands.",
    neighbors: ["Saint Lucia", "Barbados", "Grenada"],
  },
  {
    name: "Trinidad and Tobago",
    code: "tt",
    flag: "\u{1F1F9}\u{1F1F9}",
    capital: "Port of Spain",
    continent: "North America",
    population: "1.3-1.4 million",
    funFact: "Has the world's largest natural deposit of asphalt at the Pitch Lake.",
    neighbors: ["Venezuela", "Grenada", "Barbados"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SOUTH AMERICA
  // ══════════════════════════════════════════════════════════════════════════

  {
    name: "Bolivia",
    code: "bo",
    flag: "\u{1F1E7}\u{1F1F4}",
    capital: "Sucre",
    continent: "South America",
    population: "11-12 million",
    funFact: "Salar de Uyuni is the world's largest salt flat, spanning over 10,000 square kilometers.",
    neighbors: ["Brazil", "Paraguay", "Argentina", "Chile", "Peru"],
  },
  {
    name: "Guyana",
    code: "gy",
    flag: "\u{1F1EC}\u{1F1FE}",
    capital: "Georgetown",
    continent: "South America",
    population: "800-850 thousand",
    funFact: "Is the only English-speaking country in South America.",
    neighbors: ["Venezuela", "Brazil", "Suriname"],
  },
  {
    name: "Paraguay",
    code: "py",
    flag: "\u{1F1F5}\u{1F1FE}",
    capital: "Asunción",
    continent: "South America",
    population: "7-8 million",
    funFact: "Is one of the only countries whose flag has a different design on each side.",
    neighbors: ["Argentina", "Brazil", "Bolivia"],
  },
  {
    name: "Suriname",
    code: "sr",
    flag: "\u{1F1F8}\u{1F1F7}",
    capital: "Paramaribo",
    continent: "South America",
    population: "580-620 thousand",
    funFact: "Is the smallest country in South America and over 90% of its land is tropical rainforest.",
    neighbors: ["Guyana", "Brazil", "France"],
  },
  {
    name: "Venezuela",
    code: "ve",
    flag: "\u{1F1FB}\u{1F1EA}",
    capital: "Caracas",
    continent: "South America",
    population: "28-30 million",
    funFact: "Angel Falls is the world's highest uninterrupted waterfall at 979 meters.",
    neighbors: ["Colombia", "Brazil", "Guyana"],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // OCEANIA
  // ══════════════════════════════════════════════════════════════════════════

  {
    name: "Kiribati",
    code: "ki",
    flag: "\u{1F1F0}\u{1F1EE}",
    capital: "Tarawa",
    continent: "Oceania",
    population: "120-125 thousand",
    funFact: "Is the only country in the world situated in all four hemispheres.",
    neighbors: ["Marshall Islands", "Nauru", "Tuvalu"],
  },
  {
    name: "Marshall Islands",
    code: "mh",
    flag: "\u{1F1F2}\u{1F1ED}",
    capital: "Majuro",
    continent: "Oceania",
    population: "55-60 thousand",
    funFact: "Bikini Atoll, where nuclear tests were conducted, gave its name to the bikini swimsuit.",
    neighbors: ["Kiribati", "Micronesia"],
  },
  {
    name: "Micronesia",
    code: "fm",
    flag: "\u{1F1EB}\u{1F1F2}",
    capital: "Palikir",
    continent: "Oceania",
    population: "105-115 thousand",
    funFact: "Nan Madol is an ancient city built on artificial islands, sometimes called the 'Venice of the Pacific'.",
    neighbors: ["Marshall Islands", "Palau", "Papua New Guinea"],
  },
  {
    name: "Nauru",
    code: "nr",
    flag: "\u{1F1F3}\u{1F1F7}",
    capital: "Yaren",
    continent: "Oceania",
    population: "10-12 thousand",
    funFact: "Is the smallest island nation in the world at just 21 square kilometers.",
    neighbors: ["Kiribati", "Solomon Islands"],
  },
  {
    name: "Palau",
    code: "pw",
    flag: "\u{1F1F5}\u{1F1FC}",
    capital: "Ngerulmud",
    continent: "Oceania",
    population: "18-20 thousand",
    funFact: "Has a jellyfish lake where millions of golden jellyfish migrate daily and are harmless to swim with.",
    neighbors: ["Philippines", "Micronesia", "Indonesia"],
  },
  {
    name: "Samoa",
    code: "ws",
    flag: "\u{1F1FC}\u{1F1F8}",
    capital: "Apia",
    continent: "Oceania",
    population: "200-210 thousand",
    funFact: "Was the first Pacific island nation to gain independence and Robert Louis Stevenson spent his final years here.",
    neighbors: ["Tonga", "Fiji", "New Zealand"],
  },
  {
    name: "Solomon Islands",
    code: "sb",
    flag: "\u{1F1F8}\u{1F1E7}",
    capital: "Honiara",
    continent: "Oceania",
    population: "700-720 thousand",
    funFact: "Some islands use dolphin teeth as currency in traditional exchanges.",
    neighbors: ["Papua New Guinea", "Vanuatu", "Nauru"],
  },
  {
    name: "Tonga",
    code: "to",
    flag: "\u{1F1F9}\u{1F1F4}",
    capital: "Nuku'alofa",
    continent: "Oceania",
    population: "100-106 thousand",
    funFact: "Is the only remaining monarchy in the Pacific and one of the first places to see each new day.",
    neighbors: ["Fiji", "Samoa", "New Zealand"],
  },
  {
    name: "Tuvalu",
    code: "tv",
    flag: "\u{1F1F9}\u{1F1FB}",
    capital: "Funafuti",
    continent: "Oceania",
    population: "11-12 thousand",
    funFact: "Earns significant revenue from licensing its '.tv' internet domain name.",
    neighbors: ["Kiribati", "Fiji", "Samoa"],
  },
  {
    name: "Vanuatu",
    code: "vu",
    flag: "\u{1F1FB}\u{1F1FA}",
    capital: "Port Vila",
    continent: "Oceania",
    population: "300-320 thousand",
    funFact: "Land diving on Pentecost Island inspired modern bungee jumping.",
    neighbors: ["Fiji", "Solomon Islands", "New Caledonia"],
  },
];

/** All country names (sorted) for the autocomplete dropdown. */
export const countryNames: string[] = countries.map((c) => c.name).sort();

// ---------------------------------------------------------------------------
// Deterministic puzzle selection — hash the date string
// ---------------------------------------------------------------------------

function hashDate(date: string): number {
  let hash = 0;
  for (let i = 0; i < date.length; i++) {
    const ch = date.charCodeAt(i);
    hash = (hash << 5) - hash + ch;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash);
}

/** Pick today's country deterministically from the date string. */
export function getGeoPuzzle(date: string): GeoPuzzle {
  const index = hashDate(date) % countries.length;
  return {
    date,
    country: countries[index],
  };
}
