import type { Element } from "@/types/periodic-puzzle";

export const ELEMENTS: Element[] = [
  // Period 1
  { name: "Hydrogen", symbol: "H", atomicNumber: 1, period: 1, group: 1, category: "nonmetal", state: "gas", discoveryEra: "1700s", commonUse: "Rocket fuel, water" },
  { name: "Helium", symbol: "He", atomicNumber: 2, period: 1, group: 18, category: "noble gas", state: "gas", discoveryEra: "1800s", commonUse: "Balloons, cryogenics" },

  // Period 2
  { name: "Lithium", symbol: "Li", atomicNumber: 3, period: 2, group: 1, category: "alkali metal", state: "solid", discoveryEra: "1800s", commonUse: "Batteries, medication" },
  { name: "Beryllium", symbol: "Be", atomicNumber: 4, period: 2, group: 2, category: "alkaline earth metal", state: "solid", discoveryEra: "1700s", commonUse: "Aerospace alloys, X-ray windows" },
  { name: "Boron", symbol: "B", atomicNumber: 5, period: 2, group: 13, category: "metalloid", state: "solid", discoveryEra: "1800s", commonUse: "Fiberglass, detergents" },
  { name: "Carbon", symbol: "C", atomicNumber: 6, period: 2, group: 14, category: "nonmetal", state: "solid", discoveryEra: "Ancient", commonUse: "Organic chemistry, diamonds, fuel" },
  { name: "Nitrogen", symbol: "N", atomicNumber: 7, period: 2, group: 15, category: "nonmetal", state: "gas", discoveryEra: "1700s", commonUse: "Fertilizers, food preservation" },
  { name: "Oxygen", symbol: "O", atomicNumber: 8, period: 2, group: 16, category: "nonmetal", state: "gas", discoveryEra: "1700s", commonUse: "Breathing, steel production" },
  { name: "Fluorine", symbol: "F", atomicNumber: 9, period: 2, group: 17, category: "halogen", state: "gas", discoveryEra: "1800s", commonUse: "Toothpaste, Teflon" },
  { name: "Neon", symbol: "Ne", atomicNumber: 10, period: 2, group: 18, category: "noble gas", state: "gas", discoveryEra: "1800s", commonUse: "Neon signs, lasers" },

  // Period 3
  { name: "Sodium", symbol: "Na", atomicNumber: 11, period: 3, group: 1, category: "alkali metal", state: "solid", discoveryEra: "1800s", commonUse: "Table salt, street lights" },
  { name: "Magnesium", symbol: "Mg", atomicNumber: 12, period: 3, group: 2, category: "alkaline earth metal", state: "solid", discoveryEra: "1800s", commonUse: "Alloys, fireworks, supplements" },
  { name: "Aluminium", symbol: "Al", atomicNumber: 13, period: 3, group: 13, category: "post-transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Cans, foil, aircraft" },
  { name: "Silicon", symbol: "Si", atomicNumber: 14, period: 3, group: 14, category: "metalloid", state: "solid", discoveryEra: "1800s", commonUse: "Computer chips, glass" },
  { name: "Phosphorus", symbol: "P", atomicNumber: 15, period: 3, group: 15, category: "nonmetal", state: "solid", discoveryEra: "1600s", commonUse: "Fertilizers, matches" },
  { name: "Sulfur", symbol: "S", atomicNumber: 16, period: 3, group: 16, category: "nonmetal", state: "solid", discoveryEra: "Ancient", commonUse: "Gunpowder, vulcanized rubber" },
  { name: "Chlorine", symbol: "Cl", atomicNumber: 17, period: 3, group: 17, category: "halogen", state: "gas", discoveryEra: "1700s", commonUse: "Water purification, PVC" },
  { name: "Argon", symbol: "Ar", atomicNumber: 18, period: 3, group: 18, category: "noble gas", state: "gas", discoveryEra: "1800s", commonUse: "Welding, light bulbs" },

  // Period 4
  { name: "Potassium", symbol: "K", atomicNumber: 19, period: 4, group: 1, category: "alkali metal", state: "solid", discoveryEra: "1800s", commonUse: "Fertilizers, bananas" },
  { name: "Calcium", symbol: "Ca", atomicNumber: 20, period: 4, group: 2, category: "alkaline earth metal", state: "solid", discoveryEra: "1800s", commonUse: "Bones, cement, chalk" },
  { name: "Scandium", symbol: "Sc", atomicNumber: 21, period: 4, group: 3, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Aerospace alloys, sports equipment" },
  { name: "Titanium", symbol: "Ti", atomicNumber: 22, period: 4, group: 4, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Aerospace, implants, paint" },
  { name: "Vanadium", symbol: "V", atomicNumber: 23, period: 4, group: 5, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Steel alloys, batteries" },
  { name: "Chromium", symbol: "Cr", atomicNumber: 24, period: 4, group: 6, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Chrome plating, stainless steel" },
  { name: "Manganese", symbol: "Mn", atomicNumber: 25, period: 4, group: 7, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Steel production, batteries" },
  { name: "Iron", symbol: "Fe", atomicNumber: 26, period: 4, group: 8, category: "transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Construction, tools, hemoglobin" },
  { name: "Cobalt", symbol: "Co", atomicNumber: 27, period: 4, group: 9, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Batteries, blue pigment, magnets" },
  { name: "Nickel", symbol: "Ni", atomicNumber: 28, period: 4, group: 10, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Coins, stainless steel, plating" },
  { name: "Copper", symbol: "Cu", atomicNumber: 29, period: 4, group: 11, category: "transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Wiring, plumbing, coins" },
  { name: "Zinc", symbol: "Zn", atomicNumber: 30, period: 4, group: 12, category: "transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Galvanizing, sunscreen, supplements" },
  { name: "Gallium", symbol: "Ga", atomicNumber: 31, period: 4, group: 13, category: "post-transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Semiconductors, LEDs, thermometers" },
  { name: "Germanium", symbol: "Ge", atomicNumber: 32, period: 4, group: 14, category: "metalloid", state: "solid", discoveryEra: "1800s", commonUse: "Fiber optics, transistors" },
  { name: "Arsenic", symbol: "As", atomicNumber: 33, period: 4, group: 15, category: "metalloid", state: "solid", discoveryEra: "Ancient", commonUse: "Semiconductors, wood preservative" },
  { name: "Selenium", symbol: "Se", atomicNumber: 34, period: 4, group: 16, category: "nonmetal", state: "solid", discoveryEra: "1800s", commonUse: "Solar cells, glass coloring" },
  { name: "Bromine", symbol: "Br", atomicNumber: 35, period: 4, group: 17, category: "halogen", state: "liquid", discoveryEra: "1800s", commonUse: "Flame retardants, photography" },
  { name: "Krypton", symbol: "Kr", atomicNumber: 36, period: 4, group: 18, category: "noble gas", state: "gas", discoveryEra: "1800s", commonUse: "Fluorescent lamps, photography flash" },

  // Period 5
  { name: "Rubidium", symbol: "Rb", atomicNumber: 37, period: 5, group: 1, category: "alkali metal", state: "solid", discoveryEra: "1800s", commonUse: "Atomic clocks, fireworks" },
  { name: "Strontium", symbol: "Sr", atomicNumber: 38, period: 5, group: 2, category: "alkaline earth metal", state: "solid", discoveryEra: "1700s", commonUse: "Fireworks (red), magnets" },
  { name: "Yttrium", symbol: "Y", atomicNumber: 39, period: 5, group: 3, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "LEDs, superconductors, lasers" },
  { name: "Zirconium", symbol: "Zr", atomicNumber: 40, period: 5, group: 4, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Nuclear reactors, dental crowns" },
  { name: "Niobium", symbol: "Nb", atomicNumber: 41, period: 5, group: 5, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Superconducting magnets, steel alloys" },
  { name: "Molybdenum", symbol: "Mo", atomicNumber: 42, period: 5, group: 6, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Steel alloys, catalysts" },
  { name: "Technetium", symbol: "Tc", atomicNumber: 43, period: 5, group: 7, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Medical imaging" },
  { name: "Ruthenium", symbol: "Ru", atomicNumber: 44, period: 5, group: 8, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Electronics, catalysts" },
  { name: "Rhodium", symbol: "Rh", atomicNumber: 45, period: 5, group: 9, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Catalytic converters, jewelry" },
  { name: "Palladium", symbol: "Pd", atomicNumber: 46, period: 5, group: 10, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Catalytic converters, dentistry" },
  { name: "Silver", symbol: "Ag", atomicNumber: 47, period: 5, group: 11, category: "transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Jewelry, photography, electronics" },
  { name: "Cadmium", symbol: "Cd", atomicNumber: 48, period: 5, group: 12, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Batteries, pigments, coatings" },
  { name: "Indium", symbol: "In", atomicNumber: 49, period: 5, group: 13, category: "post-transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Touchscreens, solders" },
  { name: "Tin", symbol: "Sn", atomicNumber: 50, period: 5, group: 14, category: "post-transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Tin cans, solder, bronze" },
  { name: "Antimony", symbol: "Sb", atomicNumber: 51, period: 5, group: 15, category: "metalloid", state: "solid", discoveryEra: "Ancient", commonUse: "Flame retardants, batteries" },
  { name: "Tellurium", symbol: "Te", atomicNumber: 52, period: 5, group: 16, category: "metalloid", state: "solid", discoveryEra: "1700s", commonUse: "Solar cells, thermoelectrics" },
  { name: "Iodine", symbol: "I", atomicNumber: 53, period: 5, group: 17, category: "halogen", state: "solid", discoveryEra: "1800s", commonUse: "Disinfectants, thyroid health" },
  { name: "Xenon", symbol: "Xe", atomicNumber: 54, period: 5, group: 18, category: "noble gas", state: "gas", discoveryEra: "1800s", commonUse: "Headlights, anesthesia, ion engines" },

  // Period 6
  { name: "Caesium", symbol: "Cs", atomicNumber: 55, period: 6, group: 1, category: "alkali metal", state: "solid", discoveryEra: "1800s", commonUse: "Atomic clocks, drilling fluids" },
  { name: "Barium", symbol: "Ba", atomicNumber: 56, period: 6, group: 2, category: "alkaline earth metal", state: "solid", discoveryEra: "1800s", commonUse: "Medical imaging, fireworks (green)" },

  // Lanthanides (group 0)
  { name: "Lanthanum", symbol: "La", atomicNumber: 57, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Camera lenses, catalysts" },
  { name: "Cerium", symbol: "Ce", atomicNumber: 58, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Catalytic converters, lighter flints" },
  { name: "Praseodymium", symbol: "Pr", atomicNumber: 59, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Magnets, aircraft engines" },
  { name: "Neodymium", symbol: "Nd", atomicNumber: 60, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Strong magnets, lasers" },
  { name: "Promethium", symbol: "Pm", atomicNumber: 61, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1900s", commonUse: "Nuclear batteries, luminous paint" },
  { name: "Samarium", symbol: "Sm", atomicNumber: 62, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Magnets, cancer treatment" },
  { name: "Europium", symbol: "Eu", atomicNumber: 63, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Euro banknote phosphors, LEDs" },
  { name: "Gadolinium", symbol: "Gd", atomicNumber: 64, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "MRI contrast agent, nuclear reactors" },
  { name: "Terbium", symbol: "Tb", atomicNumber: 65, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Green phosphors, sonar systems" },
  { name: "Dysprosium", symbol: "Dy", atomicNumber: 66, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Magnets, nuclear reactors" },
  { name: "Holmium", symbol: "Ho", atomicNumber: 67, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Lasers, strongest magnetic poles" },
  { name: "Erbium", symbol: "Er", atomicNumber: 68, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Fiber optics, pink glass" },
  { name: "Thulium", symbol: "Tm", atomicNumber: 69, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Portable X-ray devices, lasers" },
  { name: "Ytterbium", symbol: "Yb", atomicNumber: 70, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1800s", commonUse: "Atomic clocks, stress gauges" },
  { name: "Lutetium", symbol: "Lu", atomicNumber: 71, period: 6, group: 0, category: "lanthanide", state: "solid", discoveryEra: "1900s", commonUse: "PET scanners, catalysts" },

  // Period 6 continued
  { name: "Hafnium", symbol: "Hf", atomicNumber: 72, period: 6, group: 4, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Nuclear reactor control rods" },
  { name: "Tantalum", symbol: "Ta", atomicNumber: 73, period: 6, group: 5, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Capacitors, surgical implants" },
  { name: "Tungsten", symbol: "W", atomicNumber: 74, period: 6, group: 6, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Light bulb filaments, drill bits" },
  { name: "Rhenium", symbol: "Re", atomicNumber: 75, period: 6, group: 7, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Jet engines, catalysts" },
  { name: "Osmium", symbol: "Os", atomicNumber: 76, period: 6, group: 8, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Fountain pen tips, electrical contacts" },
  { name: "Iridium", symbol: "Ir", atomicNumber: 77, period: 6, group: 9, category: "transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Spark plugs, crucibles" },
  { name: "Platinum", symbol: "Pt", atomicNumber: 78, period: 6, group: 10, category: "transition metal", state: "solid", discoveryEra: "1700s", commonUse: "Catalytic converters, jewelry" },
  { name: "Gold", symbol: "Au", atomicNumber: 79, period: 6, group: 11, category: "transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Jewelry, electronics, currency" },
  { name: "Mercury", symbol: "Hg", atomicNumber: 80, period: 6, group: 12, category: "transition metal", state: "liquid", discoveryEra: "Ancient", commonUse: "Thermometers, fluorescent lamps" },
  { name: "Thallium", symbol: "Tl", atomicNumber: 81, period: 6, group: 13, category: "post-transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Electronics, medical imaging" },
  { name: "Lead", symbol: "Pb", atomicNumber: 82, period: 6, group: 14, category: "post-transition metal", state: "solid", discoveryEra: "Ancient", commonUse: "Batteries, radiation shielding" },
  { name: "Bismuth", symbol: "Bi", atomicNumber: 83, period: 6, group: 15, category: "post-transition metal", state: "solid", discoveryEra: "1400s", commonUse: "Pepto-Bismol, cosmetics, alloys" },
  { name: "Polonium", symbol: "Po", atomicNumber: 84, period: 6, group: 16, category: "post-transition metal", state: "solid", discoveryEra: "1800s", commonUse: "Static eliminators, heat source" },
  { name: "Astatine", symbol: "At", atomicNumber: 85, period: 6, group: 17, category: "halogen", state: "solid", discoveryEra: "1900s", commonUse: "Cancer treatment research" },
  { name: "Radon", symbol: "Rn", atomicNumber: 86, period: 6, group: 18, category: "noble gas", state: "gas", discoveryEra: "1900s", commonUse: "Cancer therapy, earthquake prediction" },

  // Period 7
  { name: "Francium", symbol: "Fr", atomicNumber: 87, period: 7, group: 1, category: "alkali metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (extremely rare)" },
  { name: "Radium", symbol: "Ra", atomicNumber: 88, period: 7, group: 2, category: "alkaline earth metal", state: "solid", discoveryEra: "1800s", commonUse: "Cancer treatment, luminous paint" },

  // Actinides (group 0)
  { name: "Actinium", symbol: "Ac", atomicNumber: 89, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1800s", commonUse: "Cancer treatment, neutron source" },
  { name: "Thorium", symbol: "Th", atomicNumber: 90, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1800s", commonUse: "Nuclear fuel, gas mantles" },
  { name: "Protactinium", symbol: "Pa", atomicNumber: 91, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },
  { name: "Uranium", symbol: "U", atomicNumber: 92, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1700s", commonUse: "Nuclear power, weapons, dating rocks" },
  { name: "Neptunium", symbol: "Np", atomicNumber: 93, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Neutron detection, nuclear waste" },
  { name: "Plutonium", symbol: "Pu", atomicNumber: 94, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Nuclear power, space probes" },
  { name: "Americium", symbol: "Am", atomicNumber: 95, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Smoke detectors" },
  { name: "Curium", symbol: "Cm", atomicNumber: 96, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Space probe power, research" },
  { name: "Berkelium", symbol: "Bk", atomicNumber: 97, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },
  { name: "Californium", symbol: "Cf", atomicNumber: 98, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Neutron source, metal detection" },
  { name: "Einsteinium", symbol: "Es", atomicNumber: 99, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },
  { name: "Fermium", symbol: "Fm", atomicNumber: 100, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },
  { name: "Mendelevium", symbol: "Md", atomicNumber: 101, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },
  { name: "Nobelium", symbol: "No", atomicNumber: 102, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },
  { name: "Lawrencium", symbol: "Lr", atomicNumber: 103, period: 7, group: 0, category: "actinide", state: "solid", discoveryEra: "1900s", commonUse: "Research only" },

  // Period 7 continued (superheavy elements)
  { name: "Rutherfordium", symbol: "Rf", atomicNumber: 104, period: 7, group: 4, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Dubnium", symbol: "Db", atomicNumber: 105, period: 7, group: 5, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Seaborgium", symbol: "Sg", atomicNumber: 106, period: 7, group: 6, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Bohrium", symbol: "Bh", atomicNumber: 107, period: 7, group: 7, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Hassium", symbol: "Hs", atomicNumber: 108, period: 7, group: 8, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Meitnerium", symbol: "Mt", atomicNumber: 109, period: 7, group: 9, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Darmstadtium", symbol: "Ds", atomicNumber: 110, period: 7, group: 10, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Roentgenium", symbol: "Rg", atomicNumber: 111, period: 7, group: 11, category: "transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Copernicium", symbol: "Cn", atomicNumber: 112, period: 7, group: 12, category: "transition metal", state: "liquid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Nihonium", symbol: "Nh", atomicNumber: 113, period: 7, group: 13, category: "post-transition metal", state: "solid", discoveryEra: "2000s", commonUse: "Research only (synthetic)" },
  { name: "Flerovium", symbol: "Fl", atomicNumber: 114, period: 7, group: 14, category: "post-transition metal", state: "solid", discoveryEra: "1900s", commonUse: "Research only (synthetic)" },
  { name: "Moscovium", symbol: "Mc", atomicNumber: 115, period: 7, group: 15, category: "post-transition metal", state: "solid", discoveryEra: "2000s", commonUse: "Research only (synthetic)" },
  { name: "Livermorium", symbol: "Lv", atomicNumber: 116, period: 7, group: 16, category: "post-transition metal", state: "solid", discoveryEra: "2000s", commonUse: "Research only (synthetic)" },
  { name: "Tennessine", symbol: "Ts", atomicNumber: 117, period: 7, group: 17, category: "halogen", state: "solid", discoveryEra: "2000s", commonUse: "Research only (synthetic)" },
  { name: "Oganesson", symbol: "Og", atomicNumber: 118, period: 7, group: 18, category: "noble gas", state: "solid", discoveryEra: "2000s", commonUse: "Research only (synthetic)" },
];
