// Word Ladder — change one letter at a time from start to end word

export interface WordLadderPuzzle {
  /** The starting word */
  start: string;
  /** The target word */
  end: string;
  /** One optimal solution path (start → end inclusive) */
  solution: string[];
}

// ---------------------------------------------------------------------------
// Common 4-letter words for validation
// ---------------------------------------------------------------------------

const VALID_WORDS = new Set([
  "aahs","abbe","abed","abet","able","ably","abut","abys","aces","ache",
  "acid","acme","acne","acre","acts","adds","ados","adze","aeon","afar",
  "aged","ages","agog","ague","ahem","aide","aids","aims","airs","airy",
  "ajar","akin","alas","alee","alga","ally","alms","aloe","also","alto",
  "ambo","amen","amid","ammo","amok","amps","anew","ankh","anna","ante",
  "anti","ants","apes","apse","aqua","arch","arcs","area","aria","arid",
  "arks","arms","army","arts","arty","ashy","asks","asps","atom","atop",
  "aunt","auto","avid","avow","away","awed","awes","awry","axed","axes",
  "axis","axle","baas","babe","back","bade","bags","bail","bait","bake",
  "bald","bale","balk","ball","balm","band","bane","bang","bank","bans",
  "barb","bard","bare","bark","barn","bars","base","bash","bask","bass",
  "bast","bate","bath","bats","bawd","bawl","bays","bead","beak","beam",
  "bean","bear","beat","beau","beck","beds","beef","been","beer","bees",
  "beet","bell","belt","bend","bent","berg","berm","best","bets","bevy",
  "bias","bibs","bide","bids","bier","bike","bile","bill","bind","bins",
  "bird","bite","bits","blab","blah","bled","blew","blip","blob","bloc",
  "blog","blot","blow","blue","blur","boar","boat","bobs","bock","bode",
  "bods","body","bogs","boil","bold","bole","boll","bolt","bomb","bond",
  "bone","bong","bonk","book","boom","boon","boor","boot","bops","bore",
  "born","bosh","boss","both","bout","bowl","bows","boys","brae","bran",
  "brat","bray","bred","brew","brig","brim","brio","brit","brow","brut",
  "buds","buff","bugs","bulb","bulk","bull","bump","bums","bung","bunk",
  "buns","buoy","burg","burl","burn","burp","burr","bury","bush","bust",
  "busy","butt","buys","buzz","byre","byte","cabs","cads","cafe","cage",
  "cake","calf","call","calm","came","camp","cams","cane","cans","cape",
  "caps","carb","card","care","carp","cars","cart","case","cash","cask",
  "cast","cats","cave","cede","cell","chad","chap","char","chat","chef",
  "chew","chic","chin","chip","chop","chub","chug","cite","city","clad",
  "clam","clan","clap","claw","clay","clef","clip","clod","clog","clop",
  "clot","club","clue","coal","coat","coax","cobs","cock","code","cods",
  "cogs","coif","coil","coin","coke","cold","cole","cols","colt","comb",
  "come","comp","cone","conk","cook","cool","coop","cope","cops","copy",
  "cord","core","cork","corn","cost","cote","coup","cove","cowl","cozy",
  "crab","craw","crew","crib","crop","crow","crud","cube","cubs","cuds",
  "cues","cuff","cult","cups","curb","curd","cure","curl","curt","cusp",
  "cute","cuts","cyan","czar","dabs","dace","dads","daft","dale","dame",
  "damp","dams","dane","dare","dark","darn","dart","dash","data","date",
  "dawn","days","daze","dead","deaf","deal","dean","dear","debt","deck",
  "deed","deem","deep","deer","deft","deli","demo","dens","dent","deny",
  "desk","dewy","dial","dice","died","dies","diet","digs","dime","dims",
  "dine","ding","dint","dips","dire","dirt","disc","dish","disk","dock",
  "docs","dodo","doer","does","doge","dogs","dole","dolt","dome","done",
  "dong","dons","doom","door","dope","dork","dorm","dory","dose","doss",
  "dote","dots","dour","dove","down","doze","drab","drag","dram","drat",
  "draw","dray","dree","drew","drib","drip","drop","drug","drum","drys",
  "dual","dubs","duck","duct","dude","duel","dues","duet","duff","duke",
  "dull","duly","dumb","dump","dune","dung","dunk","dupe","dusk","dust",
  "duty","dyed","dyer","dyes","dyne","each","earl","earn","ears","ease",
  "east","easy","eats","eave","ebbs","ebon","echo","ecru","eddy","edge",
  "edgy","edit","eels","eggs","egos","eked","elks","elms","else","emit",
  "ends","envy","epee","epic","eras","ergo","errs","etch","euro","even",
  "ever","eves","evil","ewer","ewes","exam","exec","exit","expo","eyed",
  "eyes","fabs","face","fact","fade","fads","fail","fain","fair","fake",
  "fall","fame","fang","fans","fare","farm","fart","fast","fate","fats",
  "fave","fawn","faze","fear","feat","feds","feed","feel","fees","feet",
  "fell","felt","fend","fern","fest","feud","fiat","fibs","fief","figs",
  "file","fill","film","find","fine","fins","fire","firm","fish","fist",
  "fits","five","fizz","flab","flag","flan","flap","flat","flaw","flax",
  "flay","flea","fled","flee","flew","flex","flip","flit","flog","flop",
  "flow","flub","flue","flux","foam","fobs","foci","foes","fogs","foil",
  "fold","folk","fond","font","food","fool","foot","ford","fore","fork",
  "form","fort","foul","four","fowl","foxy","fray","free","fret","frog",
  "from","fuel","full","fume","fund","funk","funs","furl","fury","fuse",
  "fuss","fuzz","gabs","gads","gaff","gags","gain","gait","gale","gall",
  "gals","game","gams","gang","gape","gaps","garb","gash","gasp","gate",
  "gave","gawk","gaze","gear","geld","gems","gene","gent","germ","gets",
  "ghat","gibe","gift","gigs","gild","gill","gilt","gimp","gins","gird",
  "girt","gist","give","glad","glam","glee","glen","glib","glob","glop",
  "glow","glue","glum","glut","gnar","gnaw","goad","goat","gobs","gods",
  "goer","goes","gold","golf","gone","gong","good","goof","gore","gory",
  "gosh","gout","gown","grab","gram","gran","gray","grew","grid","grim",
  "grin","grip","grit","grog","grot","grow","grub","guar","guff","gulf",
  "gull","gulp","gums","gunk","guns","guru","gush","gust","guts","guys",
  "gybe","gyms","gyre","hack","hade","haft","hags","hail","hair","hake",
  "hale","half","hall","halo","halt","hame","hams","hand","hang","hank",
  "haps","hare","hark","harm","harp","hash","hasp","hate","haul","have",
  "hawk","haws","hays","haze","hazy","head","heal","heap","hear","heat",
  "heck","heed","heel","heft","heir","held","hell","helm","help","hemp",
  "hems","hens","herb","herd","here","hero","hers","hewn","hews","hick",
  "hide","hied","high","hike","hill","hilt","hind","hint","hips","hire",
  "hiss","hits","hive","hoar","hoax","hobo","hobs","hock","hods","hoed",
  "hoes","hogs","hoke","hold","hole","holy","home","hone","honk","hood",
  "hoof","hook","hoop","hoot","hope","hops","horn","hose","host","hour",
  "howl","hubs","hued","hues","huff","huge","hugs","hulk","hull","hump",
  "hums","hung","hunk","hunt","hurl","hurt","hush","huts","hymn","hype",
  "ibex","iced","ices","icky","icon","idea","idle","idly","iffy","ills",
  "imam","imps","inch","info","inks","inky","inns","into","ions","iota",
  "iris","irks","iron","isle","itch","item","jabs","jack","jade","jags",
  "jail","jamb","jams","jape","jars","java","jaws","jays","jazz","jean",
  "jeer","jell","jerk","jest","jets","jibe","jibs","jigs","jilt","jinx",
  "jive","jobs","jock","joey","jogs","join","joke","jolt","josh","joss",
  "jots","jowl","joys","judo","jugs","jump","june","junk","jury","just",
  "jute","juts","kale","keen","keep","kegs","kelp","kemp","kepi","kept",
  "kern","keys","kick","kids","kill","kiln","kilo","kilt","kind","king",
  "kink","kins","kips","kiss","kite","kits","knee","knew","knit","knob",
  "knot","know","knur","labs","lace","lack","lacs","lacy","lads","laid",
  "lain","lair","lake","lamb","lame","lamp","lams","land","lane","lank",
  "laps","lard","lark","lase","lash","lass","last","late","lath","lats",
  "laud","lava","lave","lawn","laws","lays","lazy","lead","leaf","leak",
  "lean","leap","leas","lech","leer","lees","left","leis","lend","lens",
  "lent","less","lest","lets","levy","liar","lice","lick","lids","lied",
  "lien","lies","lieu","life","lift","like","lilt","limb","lime","limo",
  "limp","limy","line","ling","link","lino","lint","lion","lips","lira",
  "lire","list","live","load","loaf","loam","loan","lobe","lobs","loch",
  "lock","lode","loft","loge","logo","logs","loin","loll","lone","long",
  "look","loom","loon","loop","loot","lops","lord","lore","lorn","lose",
  "loss","lost","loth","lots","loud","lour","lout","love","lows","lube",
  "luce","luck","ludo","luge","lull","lump","lune","lung","lure","lurk",
  "lush","lust","lute","lynx","lyre","mace","mach","macs","made","mads",
  "maid","mail","maim","main","make","male","mall","malt","mams","mane",
  "maps","mare","mark","mars","mash","mask","mass","mast","mate","math",
  "mats","maul","maws","maze","mead","meal","mean","meat","meek","meet",
  "meld","melt","memo","mend","menu","mere","mesh","mess","mete","mica",
  "mice","mien","miff","mike","mild","mile","milk","mill","mils","milt",
  "mime","mind","mine","mini","mink","mint","minx","mire","mirk","miss",
  "mist","mite","mitt","moan","moat","mobs","mock","mode","mods","moil",
  "mojo","mold","mole","molt","moms","monk","mood","moon","moor","moot",
  "mope","mops","more","morn","moss","most","moth","moue","move","much",
  "muck","muds","muff","mugs","mule","mull","mumm","mums","mung","murk",
  "muse","mush","musk","must","mute","mutt","myth","naan","nabs","nags",
  "naif","nail","name","nape","naps","narc","nave","navy","near","neat",
  "neck","need","neem","neon","nerd","nest","nets","news","newt","next",
  "nibs","nice","nick","nine","nips","nits","nobs","nock","node","nods",
  "noel","none","nook","noon","norm","nose","note","noun","nova","nubs",
  "nude","null","numb","nuns","nuts","oafs","oaks","oars","oath","oats",
  "obey","oboe","odds","odor","offs","ogle","ogre","oils","oily","oink",
  "okay","okra","olds","oleo","omen","omit","once","ones","only","onto",
  "oops","ooze","opal","open","opts","opus","oral","orbs","orca","ores",
  "ouch","ours","oust","outs","oval","oven","over","owed","owes","owls",
  "owns","oxen","oxes","pace","pack","pact","pads","page","paid","pail",
  "pain","pair","pale","pall","palm","pals","pane","pang","pans","pard",
  "pare","park","pars","part","pass","past","path","pats","pave","pawl",
  "pawn","paws","pays","peak","peal","pear","peas","peat","peck","pecs",
  "peel","peer","pegs","pelt","pend","pens","peon","peps","perk","perm",
  "pert","peso","pest","pets","pews","phat","phew","pick","pied","pier",
  "pigs","pike","pile","pill","pimp","pine","pink","pins","pint","pion",
  "pipe","pips","pith","pits","pity","plan","plat","play","plea","plod",
  "plop","plot","plow","ploy","plug","plum","plus","pods","poem","poet",
  "poke","pole","poll","polo","pomp","pond","pone","pony","pool","poop",
  "poor","pope","pops","pore","pork","port","pose","posh","post","posy",
  "pots","pour","pout","pray","prep","prey","prig","prim","proa","prod",
  "prom","prop","pros","prow","pubs","puce","puck","puds","puff","pugs",
  "pull","pulp","puma","pump","punk","puns","punt","pups","pure","purr",
  "push","puts","putt","quad","quag","quay","quid","quip","quit","quiz",
  "race","rack","racy","rads","raft","rage","rags","raid","rail","rain",
  "rake","ramp","rams","rang","rank","rant","raps","rare","rash","rasp",
  "rate","rats","rave","rays","raze","read","real","ream","reap","rear",
  "rebs","redo","reds","reed","reef","reek","reel","refs","rein","rely",
  "rend","rent","rest","ribs","rice","rich","rick","ride","rids","rife",
  "rift","rigs","rile","rill","rime","rims","rind","ring","rink","riot",
  "ripe","rips","rise","risk","rite","road","roam","roan","roar","robe",
  "robs","rock","rode","rods","roes","roil","role","roll","romp","roof",
  "rook","room","root","rope","rose","rosy","rote","rots","roue","rout",
  "rove","rows","rubs","ruby","ruck","rude","rued","rues","ruff","rugs",
  "ruin","rule","rump","rune","rung","runs","runt","ruse","rush","rust",
  "ruts","ryes","sack","sacs","safe","saga","sage","sago","sags","said",
  "sail","sake","sale","salt","same","sand","sane","sang","sank","saps",
  "sari","sash","sass","save","saws","says","scab","scad","scam","scan",
  "scar","seal","seam","sear","seas","seat","sect","seed","seek","seem",
  "seen","seep","seer","self","sell","semi","send","sent","sept","sera",
  "serf","sets","sewn","shag","sham","shed","shim","shin","ship","shiv",
  "shod","shoe","shoo","shop","shot","show","shul","shun","shut","sick",
  "side","sift","sigh","sign","silk","sill","silo","silt","sine","sing",
  "sink","sips","sire","site","sits","size","skag","skid","skim","skin",
  "skip","skit","slab","slag","slam","slap","slat","slaw","slay","sled",
  "slew","slid","slim","slit","slob","sloe","slog","slop","slot","slow",
  "slub","slue","slug","slum","slur","smog","snag","snap","snip","snit",
  "snob","snot","snow","snub","snug","soak","soap","soar","sobs","sock",
  "soda","sods","sofa","soft","soil","sold","sole","soma","some","song",
  "sons","soon","soot","sops","sore","sort","soul","soup","sour","span",
  "spar","spas","spat","spec","sped","spew","spin","spit","spot","spry",
  "spud","spun","spur","stab","stag","star","stay","stem","step","stew",
  "stir","stop","stow","stub","stud","stun","subs","such","suck","suds",
  "suit","sulk","sums","sung","sunk","suns","sups","sure","surf","swan",
  "swap","sway","swim","swum","sync","tabs","tack","taco","tact","tads",
  "tags","tail","take","tale","talk","tall","tame","tamp","tang","tank",
  "tans","tape","taps","tarn","taro","tarp","tars","tart","task","taxa",
  "taxi","teak","teal","team","tear","teas","teen","tell","temp","tend",
  "tens","tent","term","tern","test","text","than","that","thaw","them",
  "then","they","thin","this","thud","thug","thus","tick","tide","tidy",
  "tied","tier","ties","tile","till","tilt","time","tine","ting","tins",
  "tiny","tips","tire","toad","toed","toes","tofu","toga","togs","toil",
  "told","tole","toll","tomb","tome","tone","tong","tons","took","tool",
  "tops","tore","torn","tort","tosh","toss","tote","tour","tout","town",
  "toys","tram","trap","tray","tree","trek","trim","trio","trip","trod",
  "trot","true","tsar","tube","tubs","tuck","tuft","tugs","tuna","tune",
  "turd","turf","turn","tusk","twin","twit","type","typo","ugly","undo",
  "unit","unto","upon","urge","urns","used","user","uses","vain","vale",
  "vamp","vane","vans","vary","vase","vast","vats","veal","veer","veil",
  "vein","vend","vent","verb","very","vest","veto","vets","vial","vibe",
  "vice","vied","vies","view","vile","vine","visa","vise","void","volt",
  "vote","vows","wade","wadi","wads","waft","wage","wags","wail","wait",
  "wake","wale","walk","wall","wand","wane","want","ward","ware","warm",
  "warn","warp","wars","wart","wary","wash","wasp","watt","wave","wavy",
  "waxy","ways","weak","weal","wean","wear","webs","weds","weed","week",
  "weft","weld","well","welt","wend","went","were","west","wets","what",
  "when","whet","whey","whim","whip","whir","whit","whom","wick","wide",
  "wife","wigs","wild","wile","will","wilt","wily","wimp","wind","wine",
  "wing","wink","wins","wipe","wire","wise","wish","wisp","with","wits",
  "woes","woke","woks","wolf","womb","wont","wood","woof","wool","word",
  "wore","work","worm","worn","wort","wove","wrap","wren","writ","wuss",
  "yack","yaks","yams","yank","yaps","yard","yarn","yawn","yawp","year",
  "yell","yelp","yens","yews","yoga","yogi","yoke","yolk","yore","your",
  "yowl","yurt","zany","zaps","zeal","zeds","zees","zero","zest","zinc",
  "zing","zips","zone","zonk","zoom","zoos",
]);

/** Check if a word is valid */
export function isValidWord(word: string): boolean {
  return VALID_WORDS.has(word.toLowerCase());
}

/** Check if two words differ by exactly one letter */
export function differsByOneLetter(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diffs = 0;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) diffs++;
    if (diffs > 1) return false;
  }
  return diffs === 1;
}

// ---------------------------------------------------------------------------
// BFS-validated puzzles — every step changes exactly 1 letter and all
// intermediate words exist in VALID_WORDS.
// ---------------------------------------------------------------------------

const SAFE_PUZZLES: WordLadderPuzzle[] = [
  { start: "cold", end: "warm", solution: ["cold", "cord", "card", "ward", "warm"] },
  { start: "head", end: "tail", solution: ["head", "heal", "hell", "hall", "hail", "tail"] },
  { start: "fast", end: "slow", solution: ["fast", "fest", "feat", "flat", "flaw", "flow", "slow"] },
  { start: "rise", end: "fall", solution: ["rise", "rile", "file", "fill", "fall"] },
  { start: "mice", end: "cats", solution: ["mice", "mite", "bite", "bits", "bats", "cats"] },
  { start: "hill", end: "vale", solution: ["hill", "hall", "hale", "vale"] },
  { start: "five", end: "four", solution: ["five", "file", "fill", "fall", "fail", "foil", "foul", "four"] },
  { start: "bell", end: "ring", solution: ["bell", "ball", "bald", "band", "bang", "rang", "ring"] },
  { start: "wine", end: "beer", solution: ["wine", "wind", "bind", "bend", "bead", "bear", "beer"] },
  { start: "hunt", end: "fish", solution: ["hunt", "hint", "mint", "mist", "fist", "fish"] },
  { start: "boot", end: "shoe", solution: ["boot", "soot", "shot", "shoe"] },
  { start: "lead", end: "gold", solution: ["lead", "head", "held", "hold", "gold"] },
  { start: "fire", end: "cool", solution: ["fire", "fore", "core", "cork", "cook", "cool"] },
  { start: "book", end: "read", solution: ["book", "boom", "room", "roam", "road", "read"] },
  { start: "warm", end: "cold", solution: ["warm", "ward", "card", "cord", "cold"] },
  { start: "meal", end: "dish", solution: ["meal", "meat", "feat", "fest", "fist", "fish", "dish"] },
  { start: "road", end: "lane", solution: ["road", "load", "lead", "lend", "land", "lane"] },
  { start: "cake", end: "cook", solution: ["cake", "care", "core", "cork", "cook"] },
  { start: "rock", end: "sand", solution: ["rock", "rack", "rank", "sank", "sand"] },
  { start: "hope", end: "wish", solution: ["hope", "hose", "rose", "rise", "wise", "wish"] },
  { start: "dark", end: "lamp", solution: ["dark", "dare", "dame", "damp", "lamp"] },
  { start: "love", end: "hate", solution: ["love", "cove", "cave", "have", "hate"] },
  { start: "work", end: "play", solution: ["work", "fork", "fort", "foot", "soot", "slot", "plot", "ploy", "play"] },
  { start: "fish", end: "bird", solution: ["fish", "fist", "mist", "mint", "mind", "bind", "bird"] },
  { start: "pork", end: "beef", solution: ["pork", "perk", "peak", "beak", "bean", "been", "beef"] },
  { start: "kite", end: "soar", solution: ["kite", "site", "sits", "sets", "seas", "sear", "soar"] },
  { start: "hide", end: "seek", solution: ["hide", "hire", "here", "herd", "heed", "seed", "seek"] },
  { start: "salt", end: "lime", solution: ["salt", "sale", "same", "lame", "lime"] },
  { start: "king", end: "rule", solution: ["king", "ring", "rung", "rune", "rule"] },
  { start: "bare", end: "cold", solution: ["bare", "bale", "bald", "bold", "cold"] },
  { start: "rich", end: "poor", solution: ["rich", "rice", "rile", "pile", "pole", "poll", "pool", "poor"] },
  { start: "wild", end: "tame", solution: ["wild", "mild", "mile", "tile", "tale", "tame"] },
  { start: "gain", end: "lose", solution: ["gain", "main", "maid", "laid", "land", "lane", "lone", "lose"] },
  { start: "tall", end: "tiny", solution: ["tall", "tale", "tile", "tine", "tiny"] },
  { start: "loud", end: "hush", solution: ["loud", "lord", "lore", "lose", "lost", "lust", "lush", "hush"] },
  { start: "east", end: "west", solution: ["east", "fast", "fest", "west"] },
  { start: "more", end: "less", solution: ["more", "lore", "lose", "loss", "less"] },
  { start: "best", end: "last", solution: ["best", "lest", "last"] },
  { start: "life", end: "dead", solution: ["life", "line", "mine", "mind", "mend", "mead", "dead"] },
  { start: "make", end: "ruin", solution: ["make", "male", "mall", "mail", "rail", "rain", "ruin"] },
  { start: "save", end: "lose", solution: ["save", "cave", "cove", "love", "lose"] },
  { start: "warm", end: "cool", solution: ["warm", "ward", "word", "wood", "wool", "cool"] },
  { start: "dull", end: "keen", solution: ["dull", "dual", "deal", "dean", "bean", "been", "keen"] },
  { start: "bulk", end: "slim", solution: ["bulk", "sulk", "sunk", "sank", "sand", "said", "slid", "slim"] },
  { start: "bear", end: "deer", solution: ["bear", "dear", "deer"] },
  { start: "mare", end: "colt", solution: ["mare", "care", "core", "cole", "colt"] },
  { start: "duck", end: "swan", solution: ["duck", "dock", "sock", "soak", "soap", "swap", "swan"] },
  { start: "soup", end: "stew", solution: ["soup", "soap", "slap", "slaw", "slew", "stew"] },
  { start: "rice", end: "corn", solution: ["rice", "race", "rare", "care", "core", "corn"] },
  { start: "meat", end: "bean", solution: ["meat", "beat", "bean"] },
  { start: "bake", end: "cook", solution: ["bake", "cake", "care", "core", "cork", "cook"] },
  { start: "milk", end: "beer", solution: ["milk", "mild", "meld", "mead", "bead", "bear", "beer"] },
  { start: "tart", end: "cake", solution: ["tart", "cart", "care", "cake"] },
  { start: "coal", end: "gold", solution: ["coal", "coat", "colt", "cold", "gold"] },
  { start: "rain", end: "snow", solution: ["rain", "raid", "said", "slid", "sled", "slew", "slow", "snow"] },
  { start: "moon", end: "star", solution: ["moon", "moan", "mean", "bean", "bear", "sear", "star"] },
  { start: "lake", end: "pond", solution: ["lake", "bake", "bane", "band", "bond", "pond"] },
  { start: "leaf", end: "stem", solution: ["leaf", "deaf", "dead", "deed", "seed", "seem", "stem"] },
  { start: "wave", end: "surf", solution: ["wave", "cave", "care", "cure", "sure", "surf"] },
  { start: "dune", end: "sand", solution: ["dune", "dane", "sane", "sand"] },
  { start: "walk", end: "runs", solution: ["walk", "talk", "tank", "rank", "rang", "rung", "runs"] },
  { start: "talk", end: "yell", solution: ["talk", "tall", "tell", "yell"] },
  { start: "kick", end: "ball", solution: ["kick", "sick", "silk", "sill", "bill", "ball"] },
  { start: "read", end: "book", solution: ["read", "bead", "beat", "boat", "boot", "book"] },
  { start: "push", end: "pull", solution: ["push", "mush", "muse", "mule", "mull", "pull"] },
  { start: "hand", end: "foot", solution: ["hand", "band", "bond", "fond", "food", "foot"] },
  { start: "hair", end: "bald", solution: ["hair", "hail", "hall", "ball", "bald"] },
  { start: "bone", end: "skin", solution: ["bone", "cone", "core", "corn", "coin", "chin", "shin", "skin"] },
  { start: "heel", end: "toes", solution: ["heel", "feel", "fuel", "duel", "dues", "does", "toes"] },
  { start: "face", end: "mask", solution: ["face", "fare", "mare", "mark", "mask"] },
  { start: "chin", end: "neck", solution: ["chin", "coin", "corn", "cork", "pork", "perk", "peck", "neck"] },
  { start: "palm", end: "fist", solution: ["palm", "pale", "male", "malt", "mast", "fast", "fist"] },
  { start: "limb", end: "bone", solution: ["limb", "lime", "line", "lone", "bone"] },
  { start: "door", end: "gate", solution: ["door", "moor", "mood", "mold", "mole", "male", "gale", "gate"] },
  { start: "wall", end: "door", solution: ["wall", "tall", "toll", "poll", "pool", "poor", "door"] },
  { start: "roof", end: "dome", solution: ["roof", "root", "soot", "sort", "sore", "some", "dome"] },
  { start: "rope", end: "cord", solution: ["rope", "cope", "core", "cord"] },
  { start: "nail", end: "bolt", solution: ["nail", "mail", "mall", "malt", "molt", "bolt"] },
  { start: "wire", end: "cord", solution: ["wire", "wore", "core", "cord"] },
  { start: "knob", end: "bolt", solution: ["knob", "snob", "slob", "slot", "soot", "boot", "bolt"] },
  { start: "town", end: "city", solution: ["town", "torn", "corn", "core", "cure", "cute", "cite", "city"] },
  { start: "home", end: "fort", solution: ["home", "come", "core", "fore", "fort"] },
  { start: "farm", end: "barn", solution: ["farm", "fare", "bare", "barn"] },
  { start: "park", end: "wood", solution: ["park", "pork", "work", "word", "wood"] },
  { start: "hall", end: "room", solution: ["hall", "ball", "bald", "bold", "bolt", "boot", "boom", "room"] },
  { start: "port", end: "dock", solution: ["port", "pork", "perk", "peck", "deck", "dock"] },
  { start: "cave", end: "mine", solution: ["cave", "cane", "mane", "mine"] },
  { start: "word", end: "poem", solution: ["word", "ford", "fort", "port", "poet", "poem"] },
  { start: "joke", end: "jest", solution: ["joke", "poke", "pose", "post", "pest", "jest"] },
  { start: "myth", end: "lore", solution: ["myth", "math", "mate", "mare", "more", "lore"] },
  { start: "fate", end: "doom", solution: ["fate", "fare", "fore", "form", "foam", "roam", "room", "doom"] },
  { start: "risk", end: "safe", solution: ["risk", "rink", "sink", "sank", "sane", "safe"] },
  { start: "debt", end: "paid", solution: ["debt", "dent", "sent", "send", "sand", "said", "paid"] },
  { start: "fear", end: "bold", solution: ["fear", "bear", "bead", "bend", "bond", "bold"] },
  { start: "rage", end: "calm", solution: ["rage", "page", "pale", "palm", "calm"] },
  { start: "zeal", end: "fire", solution: ["zeal", "heal", "head", "herd", "here", "hire", "fire"] },
  { start: "plea", end: "pray", solution: ["plea", "flea", "flew", "flaw", "claw", "clay", "play", "pray"] },
  { start: "worm", end: "bird", solution: ["worm", "form", "ford", "fond", "bond", "bind", "bird"] },
  { start: "sail", end: "dock", solution: ["sail", "said", "sand", "sank", "sack", "sock", "dock"] },
  { start: "gift", end: "give", solution: ["gift", "lift", "life", "live", "give"] },
  { start: "mold", end: "cure", solution: ["mold", "cold", "cord", "core", "cure"] },
  { start: "pest", end: "cure", solution: ["pest", "past", "cast", "cart", "care", "cure"] },
  { start: "band", end: "song", solution: ["band", "sand", "sang", "song"] },
  { start: "film", end: "reel", solution: ["film", "fill", "fell", "feel", "reel"] },
  { start: "fort", end: "wall", solution: ["fort", "font", "wont", "want", "wait", "wail", "wall"] },
  { start: "ship", end: "dock", solution: ["ship", "snip", "snap", "soap", "soak", "sock", "dock"] },
  { start: "poll", end: "vote", solution: ["poll", "pole", "role", "rote", "vote"] },
  { start: "dime", end: "coin", solution: ["dime", "dome", "come", "core", "corn", "coin"] },
  { start: "plow", end: "farm", solution: ["plow", "slow", "slot", "soot", "foot", "fort", "form", "farm"] },
  { start: "haze", end: "mist", solution: ["haze", "maze", "male", "malt", "mast", "mist"] },
  { start: "foam", end: "wave", solution: ["foam", "form", "fore", "wore", "wove", "wave"] },
  { start: "burn", end: "cool", solution: ["burn", "born", "corn", "coin", "coil", "cool"] },
  { start: "melt", end: "cold", solution: ["melt", "molt", "colt", "cold"] },
  { start: "sore", end: "heal", solution: ["sore", "lore", "lord", "load", "lead", "head", "heal"] },
  { start: "lost", end: "find", solution: ["lost", "most", "mist", "mint", "mind", "find"] },
  { start: "slam", end: "door", solution: ["slam", "seam", "sear", "soar", "sour", "pour", "poor", "door"] },
  { start: "sail", end: "wind", solution: ["sail", "said", "sand", "wand", "wind"] },
  { start: "tide", end: "wave", solution: ["tide", "wide", "wade", "wave"] },
  { start: "robe", end: "vest", solution: ["robe", "rose", "lose", "lost", "lest", "vest"] },
  { start: "lark", end: "song", solution: ["lark", "bark", "bank", "bang", "sang", "song"] },
  { start: "cord", end: "rope", solution: ["cord", "core", "cope", "rope"] },
  { start: "mane", end: "hair", solution: ["mane", "male", "hale", "hall", "hail", "hair"] },
  { start: "nest", end: "bird", solution: ["nest", "best", "bent", "bend", "bind", "bird"] },
  { start: "coal", end: "fire", solution: ["coal", "coil", "coin", "corn", "core", "fore", "fire"] },
  { start: "lure", end: "hook", solution: ["lure", "cure", "core", "cork", "cook", "hook"] },
  { start: "pawn", end: "king", solution: ["pawn", "pain", "paid", "said", "sand", "sang", "sing", "king"] },
  { start: "sage", end: "wise", solution: ["sage", "wage", "wade", "wide", "wise"] },
  { start: "duke", end: "earl", solution: ["duke", "dune", "dane", "dare", "darn", "earn", "earl"] },
  { start: "gust", end: "wind", solution: ["gust", "must", "mist", "mint", "mind", "wind"] },
  { start: "tomb", end: "dead", solution: ["tomb", "tome", "home", "hole", "hold", "held", "head", "dead"] },
  { start: "cure", end: "heal", solution: ["cure", "curl", "hurl", "hull", "hell", "heal"] },
  { start: "muse", end: "poem", solution: ["muse", "must", "most", "post", "poet", "poem"] },
  { start: "rune", end: "code", solution: ["rune", "rude", "rode", "code"] },
  { start: "myth", end: "tale", solution: ["myth", "math", "mate", "male", "tale"] },
  { start: "yarn", end: "tale", solution: ["yarn", "barn", "bare", "bale", "tale"] },
  { start: "moat", end: "fort", solution: ["moat", "boat", "boot", "foot", "fort"] },
  { start: "oath", end: "bond", solution: ["oath", "math", "mate", "mane", "bane", "band", "bond"] },
  { start: "gold", end: "mine", solution: ["gold", "mold", "mild", "mind", "mine"] },
  { start: "calm", end: "rage", solution: ["calm", "palm", "pale", "page", "rage"] },
  { start: "dirt", end: "soil", solution: ["dirt", "dart", "wart", "wait", "wail", "sail", "soil"] },
  { start: "sled", end: "snow", solution: ["sled", "slew", "slow", "snow"] },
  { start: "math", end: "test", solution: ["math", "bath", "bats", "bass", "lass", "last", "lest", "test"] },
  { start: "cash", end: "gold", solution: ["cash", "cast", "cost", "colt", "cold", "gold"] },
  { start: "hurt", end: "heal", solution: ["hurt", "hurl", "hull", "hell", "heal"] },
  { start: "warm", end: "fire", solution: ["warm", "farm", "fare", "fire"] },
  { start: "cool", end: "wind", solution: ["cool", "fool", "food", "fond", "find", "wind"] },
  { start: "silk", end: "lace", solution: ["silk", "sick", "lick", "lack", "lace"] },
  { start: "spin", end: "turn", solution: ["spin", "shin", "chin", "coin", "corn", "torn", "turn"] },
  { start: "mask", end: "face", solution: ["mask", "mark", "mare", "fare", "face"] },
  { start: "song", end: "tune", solution: ["song", "long", "lone", "tone", "tune"] },
  { start: "fool", end: "sage", solution: ["fool", "pool", "poll", "pole", "sole", "sale", "sage"] },
  { start: "cork", end: "wine", solution: ["cork", "core", "wore", "wire", "wine"] },
  { start: "gate", end: "door", solution: ["gate", "mate", "male", "mole", "mold", "mood", "moor", "door"] },
  { start: "bolt", end: "lock", solution: ["bolt", "boot", "book", "look", "lock"] },
  { start: "rake", end: "leaf", solution: ["rake", "lake", "lane", "land", "lend", "lead", "leaf"] },
  { start: "wand", end: "wave", solution: ["wand", "sand", "sane", "save", "wave"] },
  { start: "peel", end: "rind", solution: ["peel", "reel", "reed", "rend", "rind"] },
  { start: "bean", end: "soup", solution: ["bean", "bear", "sear", "soar", "soap", "soup"] },
  { start: "bait", end: "hook", solution: ["bait", "wait", "wail", "tail", "toil", "tool", "took", "hook"] },
  { start: "comb", end: "hair", solution: ["comb", "come", "cole", "hole", "hale", "hall", "hail", "hair"] },
  { start: "foam", end: "beer", solution: ["foam", "roam", "roar", "rear", "bear", "beer"] },
  { start: "desk", end: "work", solution: ["desk", "deck", "peck", "perk", "pork", "work"] },
  { start: "bone", end: "meal", solution: ["bone", "bond", "bend", "bead", "mead", "meal"] },
  { start: "cape", end: "hero", solution: ["cape", "care", "hare", "here", "hero"] },
  { start: "dice", end: "game", solution: ["dice", "dace", "dame", "game"] },
  { start: "fuse", end: "bomb", solution: ["fuse", "fume", "fame", "came", "come", "comb", "bomb"] },
  { start: "gale", end: "wind", solution: ["gale", "bale", "bane", "band", "wand", "wind"] },
  { start: "herd", end: "farm", solution: ["herd", "here", "hare", "fare", "farm"] },
  { start: "mint", end: "coin", solution: ["mint", "mind", "find", "fond", "ford", "cord", "corn", "coin"] },
  { start: "pave", end: "road", solution: ["pave", "pare", "pore", "lore", "lord", "load", "road"] },
  { start: "torn", end: "mend", solution: ["torn", "born", "bore", "bone", "bond", "bend", "mend"] },
  { start: "warp", end: "bend", solution: ["warp", "ward", "wand", "band", "bend"] },
  { start: "dome", end: "roof", solution: ["dome", "some", "sore", "sort", "soot", "root", "roof"] },
  { start: "flag", end: "pole", solution: ["flag", "flat", "feat", "meat", "moat", "molt", "mole", "pole"] },
  { start: "jade", end: "gold", solution: ["jade", "made", "mode", "mole", "mold", "gold"] },
  { start: "mast", end: "sail", solution: ["mast", "malt", "mall", "mail", "sail"] },
  { start: "stew", end: "soup", solution: ["stew", "slew", "slaw", "slap", "soap", "soup"] },
  { start: "tusk", end: "bone", solution: ["tusk", "task", "tank", "bank", "bane", "bone"] },
  { start: "wilt", end: "fade", solution: ["wilt", "hilt", "halt", "hale", "male", "made", "fade"] },
  { start: "yoke", end: "bond", solution: ["yoke", "poke", "pore", "bore", "bone", "bond"] },
  { start: "zoom", end: "fast", solution: ["zoom", "boom", "boot", "boat", "beat", "feat", "fest", "fast"] },
  { start: "dark", end: "dawn", solution: ["dark", "darn", "dawn"] },
  { start: "cold", end: "heat", solution: ["cold", "hold", "held", "head", "heat"] },
  { start: "come", end: "gone", solution: ["come", "cone", "gone"] },
  { start: "stay", end: "left", solution: ["stay", "slay", "slat", "flat", "feat", "fest", "lest", "left"] },
  { start: "meal", end: "cook", solution: ["meal", "peal", "peak", "perk", "pork", "cork", "cook"] },
  { start: "flow", end: "drip", solution: ["flow", "plow", "prow", "prop", "drop", "drip"] },
  { start: "ruin", end: "mend", solution: ["ruin", "rain", "raid", "laid", "land", "lend", "mend"] },
  { start: "sink", end: "swim", solution: ["sink", "sank", "sand", "said", "slid", "slim", "swim"] },
  { start: "lean", end: "bulk", solution: ["lean", "bean", "beat", "belt", "bell", "bull", "bulk"] },
  { start: "fake", end: "real", solution: ["fake", "take", "tale", "tall", "tell", "teal", "real"] },
  { start: "take", end: "give", solution: ["take", "cake", "cave", "gave", "give"] },
  { start: "send", end: "mail", solution: ["send", "sand", "said", "maid", "mail"] },
  { start: "seed", end: "grow", solution: ["seed", "sled", "slew", "slow", "glow", "grow"] },
  { start: "note", end: "song", solution: ["note", "none", "lone", "long", "song"] },
  { start: "pack", end: "load", solution: ["pack", "lack", "lark", "lard", "lord", "load"] },
  { start: "harm", end: "heal", solution: ["harm", "hare", "hale", "hall", "hell", "heal"] },
  { start: "dust", end: "mite", solution: ["dust", "must", "muse", "mute", "mite"] },
  { start: "code", end: "hack", solution: ["code", "rode", "ride", "rice", "race", "rack", "hack"] },
  { start: "page", end: "book", solution: ["page", "cage", "care", "core", "cork", "cook", "book"] },
  { start: "test", end: "pass", solution: ["test", "pest", "past", "pass"] },
];

// ---------------------------------------------------------------------------
// Daily puzzle selector
// ---------------------------------------------------------------------------

function dateToDayNumber(date: string): number {
  const d = new Date(date + "T00:00:00Z");
  return Math.floor(d.getTime() / 86_400_000);
}

export function getTodayDate(): string {
  return new Date().toISOString().slice(0, 10);
}

export function getWordLadderPuzzle(date: string): WordLadderPuzzle {
  const day = dateToDayNumber(date);
  const hash = ((day * 2654435761) >>> 0) % SAFE_PUZZLES.length;
  return SAFE_PUZZLES[hash];
}

/** Return the number of seed puzzles available (used for archive generation) */
export function getSeedPuzzleCount(): number {
  return SAFE_PUZZLES.length;
}

// ---------------------------------------------------------------------------
// Supabase queries (for archive)
// ---------------------------------------------------------------------------

import { getSupabase } from "@/lib/supabase";

export async function getWordLadderArchiveDates(): Promise<{ puzzle_date: string }[]> {
  const supabase = getSupabase();
  if (!supabase) return [];

  const today = getTodayDate();
  const { data } = await supabase
    .from("word_ladder_puzzles")
    .select("puzzle_date")
    .lte("puzzle_date", today)
    .order("puzzle_date", { ascending: false });

  return data ?? [];
}

export async function getWordLadderPuzzleByDate(date: string): Promise<WordLadderPuzzle | null> {
  const supabase = getSupabase();
  if (!supabase) return null;

  const { data } = await supabase
    .from("word_ladder_puzzles")
    .select("start_word, end_word, solution")
    .eq("puzzle_date", date)
    .single();

  if (!data) return null;
  return {
    start: data.start_word,
    end: data.end_word,
    solution: data.solution,
  };
}
